### ISSUE TITLE
Fetch pending state diff and block together for Starknet v0.12.2 

### ISSUE THREAD

**Issue by IronGauntlets** [NethermindEth/juno#1003]
As described [here](https://community.starknet.io/t/introducing-p2p-authentication-and-mismatch-resolution-in-v0-12-2/97993#combined-state-diff-and-block-endpoint-4) `get_state_update` has a new boolean parameter: `includeBlock` which allows fetching of both state update and block in a single request.

For pending blocks, this is necessary, while it is not for other blocks, however, it would be good to reduce the total number of requests sent to the feeder gateway.

**Comment by Brivan-26** [comment]
Closed in favor of [this issue](https://github.com/NethermindEth/juno/issues/1089), already implemented.
