### ISSUE TITLE
Maintain `latest` and `pending` block and state in memory

### ISSUE THREAD

**Issue by IronGauntlets** [NethermindEth/juno#1007]
Juno should be able to respond within 100 microseconds for any rpc request involving the `latest` or `pending` state.  This would impact the following calls:
- `starknet_getBlockWithTxHashes`
- `starknet_getBlockWithTxs`
- `starknet_getStateUpdate`
- `starknet_getClass`
- `starknet_getBlockTransactionCount`
- `starknet_blockNumber`
- `starknet_blockHashAndNumber`
- `starknet_chainId`
- `starknet_pendingTransactions`
- `starknet_syncing`
- `starknet_getEvents`
- `starknet_getNonce`

One way to achieve such low response times is to cache the `latest` and `pending` state in memory. This would make the `Pending` bucket unnecessary therefore it should be removed.

**Comment by omerfirmak** [comment]
How about a more generalized cache in front of our DB? It would benefit us in all sorts of ways.

**Comment by IronGauntlets** [comment]
That would work as well. How do you propose we would achieve that?

**Comment by omerfirmak** [comment]
"pending" was moved in to memory in #1430 , should be good enough for now.
