### ISSUE TITLE
Handle L1 Reorg

### ISSUE THREAD

**Issue by IronGauntlets** [NethermindEth/juno#1009]
Currently, we assume Ethereum's `finalized` blocks would not be reorged as that would require 33% of the validators to be slashed. However, this is still a possibility thus it should be handled.

**Comment by omerfirmak** [comment]
> Ethereum's finalized blocks would not be reorged as that would require 33% of the validators to be slashed. However, this is still a possibility thus it should be handled.

If I recall correctly, even etheruem nodes dont handle this automatically. I dont think it makes sense to aim that.

**Comment by IronGauntlets** [comment]
You are correct and the threshold for the finalised block to be reorged is >66%, not 33%.
