### ISSUE TITLE
Simplify L1 verification

### ISSUE THREAD

**Issue by IronGauntlets** [NethermindEth/juno#1011]
Currently, we subscribe to Ethereum headers and periodically fetch the `finalized` height to determine when we can commit Starknet L1 contract log updates. Starknet L1 contract updates are similarly subscribed to which are kept in a queue waiting for finalised height and are adjusted for any Ethereum reorgs.

I think we can simplify this by polling for `finalized` height (which we already do) and fetching the Starknet L1 contract state, the benefits of this approach are as follows:
- No L2 reorg handling
- No need to maintain a queue, we can immediately commit the L1 head to Juno's DB
- User doesn't need to provide a `ws` connection

Assumptions:
- All Ethereum full nodes have the latest finalised block state
- Ethereum Finalised blocks are not reorged (see #1009)

**Comment by IronGauntlets** [comment]
Related #853

**Comment by omerfirmak** [comment]
> All Ethereum full nodes have the latest finalised block state

I dont think that is an assumption we can make. There is no consensus on how far back a full node should maintain the state.

> Ethereum Finalised blocks are not reorged (see https://github.com/NethermindEth/juno/issues/1009)

So this issue and #1009 contradicts each other, no?

**Comment by IronGauntlets** [comment]
> >Ethereum Finalised blocks are not reorged (see https://github.com/NethermindEth/juno/issues/1009)
>
> So this issue and https://github.com/NethermindEth/juno/issues/1009 contradicts each other, no?

You can make the assumption that it won't happen because it has a very low probability which we essentially do now. I was just stating the assumptions not stating whether they hold or not.


>> All Ethereum full nodes have the latest finalised block state
>
> I dont think that is an assumption we can make. There is no consensus on how far back a full node should maintain the state.

I think we should investigate more. The few articles I have read mention 128 blocks state is maintained by full nodes and `tip of chain - 96 blocks` is the latest finalised block which is more than 128 blocks.

**Comment by joshklop** [comment]
> The few articles I have read mention 128 blocks state is maintained by full node

It is an implementation detail. Geth maintains 128. Nethermind maintains 64. A Geth core dev recently said that they want to move toward a design where users specify how far back history is stored.

**Comment by IronGauntlets** [comment]
Closing this issue as no Ethereum full node guarantees latest `finalized` block state.
