### ISSUE TITLE
Make `History` private

### ISSUE THREAD

**Issue by IronGauntlets** [NethermindEth/juno#1012]
[History](https://github.com/NethermindEth/juno/blob/main/core/history.go) is used to keep track of the historical state, however, it is not used outside of the `core` package, therefore, it doesn't need to be public.

**Comment by amirhasanzadehpy** [comment]
Hey! I noticed that there is an open issue #1012 regarding making the `History` struct private. Please let me know if I can proceed with working on this issue.

Thank you!
