### ISSUE TITLE
Log warnings on error responses from feeder

### ISSUE THREAD

**Issue by joshklop** [NethermindEth/juno#1020]
Useful to notify node operators when, for example, requests are blocked by a firewall.

**Comment by aminsato** [comment]
I think 🤔  it's good idea to add completed warning that contain requested url on line [feeder.go](https://github.com/NethermindEth/juno/blob/main/clients/feeder/feeder.go?plain=#1L217)

like this

`c.log.Warnw("failed query to feeder, retrying...", "retryAfter", wait.String(), "on URL", queryURL)
`

**Comment by omerfirmak** [comment]
Done in https://github.com/NethermindEth/juno/pull/1252
