### ISSUE TITLE
Log the version number on start up

### ISSUE THREAD

**Issue by eliotstock** [NethermindEth/juno#1045]
Quote Tomasz:

> when starting Juno it would be good to display version in the logs at the beginning - this will decrease the number of wrong bug reports resulting from people not knowing which version they are running

**Comment by aminsato** [comment]
Hi
I Have Done this
Please review my pull request
#1046

**Comment by Brivan-26** [comment]
We're already logging the version on startup, [here](https://github.com/NethermindEth/juno/blob/6c340b1b22d425b66ee0a4f1e83b024ce4ca341f/node/node.go#L165)
However, it seems it needs to be nicely formatted.
