### ISSUE TITLE
Refactor `rpc.TransactionStatus` to handle the case when the Tx hash doesn't exist

### ISSUE THREAD

**Issue by Brivan-26** [NethermindEth/juno#1058]
Since some feeder's error codes were specified in v0.12.1 (including [TRANSACTION_NOT_FOUND](https://github.com/starkware-libs/cairo-lang/blob/cc86dfc40202fd74370734ef8b9414a2d78dcc06/src/starkware/starknet/definitions/error_codes.py#L67)), we should cover the case of unexisting Tx hash [here](https://github.com/NethermindEth/juno/blob/c65ecfe2cc4b4472cd1f717218a5bc649281774d/rpc/handlers.go#L1034) and send the appropriate error code

**Comment by aminsato** [comment]
Hi
I have done this #1062
please review my PR
Thanks
