### ISSUE TITLE
Transferred fee amount is wrong in trace API

### ISSUE THREAD

**Issue by omerfirmak** [NethermindEth/juno#1077]
For transaction hash "0x60a17e3a2a9ed1e6860fc4188b0d2870d66eee75d0cf853c48f182232f6e9a" in goerli

In our traceTransaction response shows that we are charging "0x182f" ETH for this transaction.

```
                    "events": [
                        {
                            "keys": [
                                "0x99cd8bde557814842a3121e8ddfd433a539b8c9f14bf31ebf108d12e6196e9"
                            ],
                            "data": [
                                "0x6f9c5ffdd87862f2a01b725962b332b13cdc81ca9e868ae049f7ffd15cb597c",
                                "0x1176a1bd84444c89232ec27754698e5d2e7e1a7f1539f12027f28b23ec9f3d8",
                                "0x182f",
                                "0x0"
                            ]
                        }
                    ],
```

but in reality it was charged "0x05a1745fe75d"

https://goerli.voyager.online/event/846376_0_2

this is due to hardcoded gas price here;
https://github.com/NethermindEth/juno/blob/main/vm/rust/src/lib.rs#L313

**Comment by kirugan** [comment]
> this is due to hardcoded gas price here;

where can we get correct value for it?

**Comment by omerfirmak** [comment]
> > this is due to hardcoded gas price here;
> 
> where can we get correct value for it?

block.Header.GasPrice

**Comment by omerfirmak** [comment]
after #1093 

```
                    "events": [
                        {
                            "keys": [
                                "0x99cd8bde557814842a3121e8ddfd433a539b8c9f14bf31ebf108d12e6196e9"
                            ],
                            "data": [
                                "0x6f9c5ffdd87862f2a01b725962b332b13cdc81ca9e868ae049f7ffd15cb597c",
                                "0x1176a1bd84444c89232ec27754698e5d2e7e1a7f1539f12027f28b23ec9f3d8",
                                "0x5a1745fe75d",
                                "0x0"
                            ]
                        }
                    ],
                    "messages": []
```

LGTM

**Comment by wojciechos** [comment]
@omerfirmak are you sure? For me current staging goerli for txn: `0x60a17e3a2a9ed1e6860fc4188b0d2870d66eee75d0cf853c48f182232f6e9a` I get:
```
            "events": [
                        {
                            "keys": [
                                "0x99cd8bde557814842a3121e8ddfd433a539b8c9f14bf31ebf108d12e6196e9"
                            ],
                            "data": [
                                "0x6f9c5ffdd87862f2a01b725962b332b13cdc81ca9e868ae049f7ffd15cb597c",
                                "0x1176a1bd84444c89232ec27754698e5d2e7e1a7f1539f12027f28b23ec9f3d8",
                                "0x5a1affab190",
                                "0x0"
                            ]
                        }
                    ],
                    "messages": []
```

which is something different than feeder response:
```
     "events": [
                    {
                        "order": 0,
                        "keys": [
                            "0x99cd8bde557814842a3121e8ddfd433a539b8c9f14bf31ebf108d12e6196e9"
                        ],
                        "data": [
                            "0x6f9c5ffdd87862f2a01b725962b332b13cdc81ca9e868ae049f7ffd15cb597c",
                            "0x1176a1bd84444c89232ec27754698e5d2e7e1a7f1539f12027f28b23ec9f3d8",
                            "0x5a1745fe75d",
                            "0x0"
                        ]
                    }
                ]
```

**Comment by wojciechos** [comment]
> @omerfirmak are you sure? For me at current staging goerli for request:
> 
> ```
> {
>     "jsonrpc": "2.0",
>     "method": "starknet_traceTransaction",
>     "params": {
>         "transaction_hash": "0x60a17e3a2a9ed1e6860fc4188b0d2870d66eee75d0cf853c48f182232f6e9a"
>     },
>     "id": 1
> }
> ```
> 
> I get:
> 
> ```
>             "events": [
>                         {
>                             "keys": [
>                                 "0x99cd8bde557814842a3121e8ddfd433a539b8c9f14bf31ebf108d12e6196e9"
>                             ],
>                             "data": [
>                                 "0x6f9c5ffdd87862f2a01b725962b332b13cdc81ca9e868ae049f7ffd15cb597c",
>                                 "0x1176a1bd84444c89232ec27754698e5d2e7e1a7f1539f12027f28b23ec9f3d8",
>                                 "0x5a1affab190",
>                                 "0x0"
>                             ]
>                         }
>                     ],
>                     "messages": []
> ```
> 
> which is something different than feeder response:
> 
> ```
>      "events": [
>                     {
>                         "order": 0,
>                         "keys": [
>                             "0x99cd8bde557814842a3121e8ddfd433a539b8c9f14bf31ebf108d12e6196e9"
>                         ],
>                         "data": [
>                             "0x6f9c5ffdd87862f2a01b725962b332b13cdc81ca9e868ae049f7ffd15cb597c",
>                             "0x1176a1bd84444c89232ec27754698e5d2e7e1a7f1539f12027f28b23ec9f3d8",
>                             "0x5a1745fe75d",
>                             "0x0"
>                         ]
>                     }
>                 ]
> ```

Copied from slack to track issue history:
```
It must be due to latest blockifier update.
They must have changed how gas is calculated.
The difference is rather small, it still might be confusing for users, that feeder/explorers display different data than Juno but not much we can do about that.
```
