### ISSUE TITLE
Support for Starknet v0.12.2

### ISSUE THREAD

**Issue by wojciechos** [NethermindEth/juno#1082]
Starknet v0.12.2 has been already deployed to integration network, we need to support it.

Current logs on integration:
```09:28:50.954 15/08/2023 +00:00	WARN	sync/sync.go:185	Failed storing Block	{"number": 308378, "hash": "0x6221...2ae7", "err": "unsupported block version"}```

**Comment by omerfirmak** [comment]
We can bump the supported version right away. There are no changes that are mandatory for 0.12.2 support.

**Comment by wojciechos** [comment]
We should release this before 21.08 because Starknet will be updating their testnets, after which Juno v0.5.0 will no longer be compatible. I'm still wondering if we are not too restrictive about versioning.
