### ISSUE TITLE
Update for Starknet's spec for write rpc: Replace DECLARE_TXN with BROADCASTED_DECLARE_TXN

### ISSUE THREAD

**Issue by wojciechos** [NethermindEth/juno#1084]
Starknet has recently updated its spec to use BROADCASTED_DECLARE_TXN instead of the older DECLARE_TXN for write rpc like estimateMessageFee or simulateTransactions. This change requires updates in how transactions are declared and the data that accompanies them. 
[commit #1](https://github.com/starkware-libs/starknet-specs/commit/cb06cf4f219a985705cf05216c3a4fe5e2eea77e)
[commit #2 ](https://github.com/starkware-libs/starknet-specs/commit/0e859ff905795f789f1dfd6f7340cdaf5015acc8)

From the updated spec, it's evident that e.g for txn declare v1 fields "sender_address", "nonce", and "class_hash" are no longer in use, with "contract_class" being the new addition.

**Comment by omerfirmak** [comment]
They are just reverting some unintentional changes that they introduced in `v0.4.0`. I dont think we will end up needing to change anything.
