### ISSUE TITLE
Wrong details in the readme configuration section

### ISSUE THREAD

**Issue by Boda805** [NethermindEth/juno#109]
**Describe the bug**
I'm getting started with the project and the configuration details in the readme aren't quite right. The config file generated is juno.yaml not config.yaml, and the directory it's held in is juno not .juno.

**Comment by stdevMac** [comment]
Thank you @Boda805 for contributing! 

Almost in each PR, we are continuos adding new features and configurations, probably in one,  we didn't update the Readme, feel free to create any issue and ask any question, you're more than welcome!
