### ISSUE TITLE
Add project description

### ISSUE THREAD

**Issue by AntiD2ta** [NethermindEth/juno#11]
**Is your feature request related to a problem? Please describe.**
The project does not have a description. This is especially good for people who see this repo for the first time. Also, this can help us to take on the community standards

**Describe the solution you'd like**
Add a concise description summarizing the project

**Comment by SaintJul** [comment]
Hi could I help with the project?

**Comment by tkstanczak** [comment]
@SaintJul yes, would be great!

**Comment by tkstanczak** [comment]
reach out to me on Discord -> @tkstanczak or same on Telegram
