### ISSUE TITLE
Move `db.CloseAndWrapOnError` to `utils` package

### ISSUE THREAD

**Issue by joshklop** [NethermindEth/juno#1116]
We can use it in the `p2p` package as well. Credit to @omerfirmak for the idea.

**Comment by Gathin23** [comment]
I would like to take up this issue. Could you explain me the details of things to be done?

**Comment by kirugan** [comment]
I think it's better to change naming from `db.CloseAndWrapOnError(...)` to `utils.RunAndWrapOnError(...)` because callback might be not related to closing smth. @joshklop wdyt?

**Comment by joshklop** [comment]
Agree.
