### ISSUE TITLE
Common adapter for feeder, gateway and rpc

### ISSUE THREAD

**Issue by rianhughes** [NethermindEth/juno#1147]
https://github.com/NethermindEth/juno/issues/1015

Crossing layers in the clean architecture requires adapter functions: input from rpc to core types should have its own adapter and input from feeder and gateway also should have their own adapters to core types (and vice versa). However, due to the commonality between all of the adapters and to reduce duplication, we created feeder2core. These functions can be moved to the utils package with a more generic name.

Further, generalise the feeder2core adapter by renaming it and moving it to the utils package.

**Comment by joshklop** [comment]
Agree that `feeder` and `gateway` should be merged, and that the renaming to `sequencer2core` makes sense.

Is the move to `utils` necessary? imho that makes the package seem more general than it actually is.
