### ISSUE TITLE
Change `sync_blocks` metric to be the current height

### ISSUE THREAD

**Issue by joshklop** [NethermindEth/juno#1152]
It increases monotonically from the time the node boots up. Even if the node boots once and never shuts down, it doesn't decrement properly in the event of a reorg.

Changing it to match the current height makes it more useful. We should probably change the name of the metric, too.

**Comment by Exca-DK** [comment]
Sounds to me like [nethermind_blockchain_height](https://docs.nethermind.io/nethermind/ethereum-client/metrics/blockchain) which is #1153

**Comment by joshklop** [comment]
Agreed, the issues overlap.
