### ISSUE TITLE
Add `rpc_server_requests_latency` Bucketed Latency Metric

### ISSUE THREAD

**Issue by wojciechos** [NethermindEth/juno#1162]
Add the bucket(histogram/heatmap) `rpc_server_requests_latency{method="starknet_syncing"}` metric, similar to what [Papyrus uses](https://github.com/starkware-libs/papyrus#metrics). This would provide:

- Detailed insights on RPC latencies.
- A focus on server-side processing, excluding network latencies - which make our load tests result more reliable.

**Comment by Exca-DK** [comment]
Should the histogram time just that? https://github.com/NethermindEth/juno/blob/121122badf30b987a3abd674d7f21581db7c0ef7/jsonrpc/server.go#L318
If yes then that whole function could be put behind middleware and rest of the server metrics could be put here eg. 
```go
func metricsMiddleware(reporter requestReporter) requestMiddleware {
	return func(ctx context.Context, req *request, handler requestHandler) (*response, error) {
		start := time.Now()
		resp, err := handler(ctx, req)
		duration := time.Since(start)
		reporter.ReportRequest(req.Method)
		reporter.ReportRequestDuration(req.Method, duration)
		if resp != nil && resp.Error != nil {
			reporter.ReportRequestError(req.Method, resp.Error.Code)
		}
		return resp, err
	}
}
```
