### ISSUE TITLE
Use golang's `slog` package

### ISSUE THREAD

**Issue by IronGauntlets** [NethermindEth/juno#1164]
Go 1.21.0 introduced [`slog`](https://pkg.go.dev/golang.org/x/exp/slog) which provides structured logging through the standard library, therefore, this should be used to remove Uber's logging package dependency.

**Comment by Exca-DK** [comment]
Are we looking at 1:1 formatting behavior here? There are some diffs in default handlers that cannot be simply achieved through `ReplaceAttr`.  1:1 Would only be achieved by writing a fully custom handler.

**Comment by Exca-DK** [comment]
Hey @IronGauntlets, while working on this issue, I noticed that this won't fully remove the Uber dependency since it's also being used by libp2p.

**Comment by IronGauntlets** [comment]
I think that is still ok as it would still remove a direct dependency. Given this is quite a recent addition to the language I would think it would take a while for the community to move away from uber's logging package.

**Comment by joshklop** [comment]
See https://github.com/NethermindEth/juno/pull/1209#issuecomment-1735273653
