### ISSUE TITLE
Generate RPC docs automatically

### ISSUE THREAD

**Issue by joshklop** [NethermindEth/juno#1184]
Use https://github.com/MetaMask/docusaurus-openrpc to generate RPC docs directly from the specs.

**Comment by 4ever9** [comment]
@joshklop Should we generate RPC docs for every version, or is it sufficient to generate it only for the latest version?

**Comment by joshklop** [comment]
Latest version is fine, if that makes things easier.

**Comment by shubham-sonthalia** [comment]
Hi @joshklop is this issue still open? Can I work on this?

**Comment by joshklop** [comment]
Feel free to work on it @shubham-sonthalia.

cc @IronGauntlets @omerfirmak

**Comment by shubham-sonthalia** [comment]
Hi @joshklop, I have added a PR for the issue. Can you pls check once?

**Comment by shubham-sonthalia** [comment]
Hi @kirugan/ @IronGauntlets / @rianhughes , could you check if the PR addresses the issue?
