### ISSUE TITLE
RPC Extract types to package 

### ISSUE THREAD

**Issue by rianhughes** [NethermindEth/juno#1247]
1. Junos rpc types should also be updated to follow the spec.

2. Juno rpc types should be extracted into its own package so that external projects (like starknet.go) can import it.

**Comment by joshklop** [comment]
> Junos rpc types should also be updated to follow the spec.

@rianhughes can you please clarify how Juno's types are out of compliance? Juno seems to follow the spec fine with its existing types.

**Comment by rianhughes** [comment]
Dumping required changes here:
BroadcastedTransaction types are deprecated

**Comment by IronGauntlets** [comment]
In my opinion, what you have pointed out is more a refactor than non-compliance with the spec.

How we internally represent certain types has no bearing on compliance. If there is a request/response which fails to follow the spec then that is an issue.

**Comment by joshklop** [comment]
> How we internally represent certain types has no bearing on compliance. If there is a request/response which fails to follow the spec then that is an issue.

Agreed. For Juno, only the json input and return values matter. However, the Go representation should match the spec as closely as possible for starknet.go (to make it easier to use for developers who are familiar with the spec). Ideally, both projects can share the same types package.

**Comment by omerfirmak** [comment]
> BroadcastedTransaction types are deprecated

They are coming back
