### ISSUE TITLE
Only poll latest block number during sync and store block number instead of the whole header

### ISSUE THREAD

**Issue by IronGauntlets** [NethermindEth/juno#1260]
In the `sync` package we periodically poll the latest block to keep track of what the latest l2 chain is. However, we do not need to fetch the whole block as we only [use the block number](https://github.com/NethermindEth/juno/pull/1253#issuecomment-1726230663).

A new option has been added on `Testnets` and `Integration` networks to only fetch the latest block numbers and hash as follows:
https://alpha4.starknet.io/feeder_gateway/get_block?blockNumber=latest&headerOnly=true

Once this is rolled out to `mainnet` we should make the relevant changes.

**Comment by joshklop** [comment]
See #1258

**Comment by IronGauntlets** [comment]
Closing as per this [comment](https://github.com/NethermindEth/juno/pull/1258#issuecomment-1727925812)
