### ISSUE TITLE
Don't over-read websocket messages

### ISSUE THREAD

**Issue by joshklop** [NethermindEth/juno#1271]
For context: https://github.com/NethermindEth/juno/pull/1266#discussion_r1334643178

I am thinking the problem be fixed by reading a full message from the connection and using `server.Handle` instead of `server.HandleReader`. We may need to allow giving an `io.Writer` to `Handle()` somehow.

**Comment by omerfirmak** [comment]
We can create a bufio.Reader before the loop and pass that to `HandleReader`. Calling bufio.NewReader on a bufio.Reader is essentially a no-op.
