### ISSUE TITLE
Transaction Trace fallback mechanism

### ISSUE THREAD

**Issue by IronGauntlets** [NethermindEth/juno#1273]
As Juno cannot create a trace for old transactions, we need a fallback mechanism to serve the old transaction traces. We have two options:
- If Juno fails to create a trace for any transaction, retrieve it from feeder gateway. Determining whether a trace has failed may not be straightforward as we would require to do some parsing on the Go side.
- Always fetch transaction trace from feeder gateway for transactions before starknet v0.12.3 and for any transaction after v0.12.3 we use the VM.

**Comment by omerfirmak** [comment]
I vote for the latter.

**Comment by IronGauntlets** [comment]
Agreed

**Comment by stranger80** [comment]
Pls reach out to StarkWare to confirm this is high priority.

**Comment by omerfirmak** [comment]
Done #1336
