### ISSUE TITLE
starknet_simulateTransactions "Skip validate is not supported"

### ISSUE THREAD

**Issue by florian-bellotti** [NethermindEth/juno#1291]
When calling method "starknet_simulateTransactions" with the simulation_flags "SKIP_VALIDATE", the server returns :

```json 
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32602,
        "message": "Invalid Params",
        "data": "Skip validate is not supported"
    },
    "id": 1
}
```

https://github.com/starkware-libs/starknet-specs/blob/59b838cdcc7b1cbf92f4249b00927185c93628e9/api/starknet_trace_api_openrpc.json#L40

**Comment by omerfirmak** [comment]
Added support for it in Juno `v0.7.5`
