### ISSUE TITLE
Juno P2P sync - design & implement initial sync

### ISSUE THREAD

**Issue by stranger80** [NethermindEth/juno#1319]
- Initial Juno sync process: 
  - Implement the ability for Juno node to run in one of two modes: 
  1. "bootstrap node" sync - syncing from from Feeder gateway, 
    - ...while it already participates in p2p communication
      - ...it serves/gossips information
      - ...it does not pull information from other p2p nodes (ie. it only syncs from Feeder gateway)
  2. "normal node" sync - syncing from other nodes, incl. the bootstrap node
    - "Block sync" design & implement logic to request information from other peers
      - make sure to validate the signatures on the received messages
    - Add telemetry metrics (eg. number of p2p peers known? ping times for peers?)

**Comment by omerfirmak** [comment]
There isn't a separate milestone like "getting to sync from a single peer first" 
We will always sync from all the peers that we are connected to.

**Comment by kirugan** [comment]
This issue was already implemented
