### ISSUE TITLE
Juno scalability - Juno DB over GRPC

### ISSUE THREAD

**Issue by stranger80** [NethermindEth/juno#1338]
Implement enhancements to improve launch time of a new Juno node in a cluster:

Launch Juno with data snapshot, but connected to other node’s DB via GRPC. While the new node’s sync process is in progress, the new node uses the other node’s DB (”parasite mode”). Once the sync is complete, the new node starts operating on the local DB (”normal mode”).

This task includes:

- [ ] Code changes required to use remote DB over GRPC
- [ ] Logic to select a "master" node for the "parasite" to connect to
- [ ] Disaster scenario handling - how does a "parasite" behave when "master" node breaks?
- [ ] Integration/load test on RPC SaaS dev infrastructure - simulate the auto-scaling scenario

**Comment by omerfirmak** [comment]
One idea;

Implement `db.DB` interface backed by a gRPC connection. That way, we can use a remote node's database to serve requests.

**Comment by omerfirmak** [comment]
[instructions](https://github.com/NethermindEth/juno/pull/1353#issuecomment-1772297798) to give #1353 a try

**Comment by omerfirmak** [comment]
This idea was shelved, extracted some of the useful code to #1404

**Comment by omerfirmak** [comment]
Done in #1353
