### ISSUE TITLE
Juno stress test pack

### ISSUE THREAD

**Issue by stranger80** [NethermindEth/juno#1347]
Implement an automated stress-testing pack for Juno, including:
- Generate a stream of Juno RPC requests against a target node to measure the average request throughput
- Allow for parameter-based control of individual request frequencies
- Fine-tune the test pack request frequencies to align with expected request load profile

The stress-test pack should be easy to reuse, so that we can re-run stress test cycles efficiently.

**Comment by wojciechos** [comment]
https://github.com/NethermindEth/starknet-rpc-tests
