### ISSUE TITLE
Improving Juno docs

### ISSUE THREAD

**Issue by Tomi-3-0** [NethermindEth/juno#1358]
Add links (e.g https://youtu.be/kh7f_Mvgpak?feature=shared) to presentations and slides by Juno team members in the docs to help improve the docs.

**Comment by LordGhostX** [comment]
Closing this issue as I could only find 3 videos on YouTube, and they don't offer any additional information beyond what's already available in the documentation.

- https://www.youtube.com/watch?v=kh7f_Mvgpak
- https://www.youtube.com/watch?v=IxEB_2GSpGA
- https://www.youtube.com/watch?v=2ZrrltCIBug

Maybe when there are more videos, I'll open this issue and create a **Presentations** page.
