### ISSUE TITLE
Benchmark test the Sticky sessions disable on RPC SaaS

### ISSUE THREAD

**Issue by stranger80** [NethermindEth/juno#1377]

**Comment by wojciechos** [comment]
We decided that it's not worth to benchmark sticky session but rather to load test one single pod. Here are the results:

# Juno v0.7.3 Load Test Report

## Test Scenario: Linear Increase of Requests/sec

**Traffic Basis:** Simulate real live traffic with wages methods

### Environment 1: Moderate Setup

- **Hardware:** 7 CPU, 14GiB RAM
- **Configuration:** `--max-vms` at 16

**Results:**
- Stable operation until ~400 req/s.
- CPU utilization reached 510% with no response delays.

**Analysis Tools:**
- Grafana
- k6

### Environment 2: Large Setup

- **Hardware:** 31 CPU, 24GiB RAM
- **Configuration:** `--max-vms` at 93

**Results:**
- Stable operation until 1550 req/s.
- CPU utilization hit ~1800% before performance degradation.

**Concerns:**
- Performance drop at this CPU usage is unexpected, needs further investigation.
