### ISSUE TITLE
Performance Degradation with Pending Poll Enabled on Pending Block Queries

### ISSUE THREAD

**Issue by wojciechos** [NethermindEth/juno#1420]
Seems like we have some performance hiccups while using pending block quieries:

1. Load tests on pending block (no pending poll): 👍 ~7.5k req/s (before response time start to increase and first error appeared)
2. Load tests on latest block (no pending poll): 👍 ~7.5k req/s
3. Load tests on latest block (with pending poll): 👍 ~7.5k req/s
4. Load tests on pending block (with pending poll): 🚨 Dropped to ~1.5k req/s

When we activate the pending poll(`--pending-poll-interval 2s`) and querying pending blocks, we're seeing a significant drop in performance. 
One of the requests:
```
{
    "jsonrpc": "2.0",
    "method": "starknet_call",
    "params": {
        "block_id": "pending",
        "request": {
            "calldata": [
                "0x05239a301b9115a60e756f4cfd8819757fd884e80554a5a896d1c0c6da09cca4"
            ],
            "contract_address": "0x049D36570D4e46f48e99674bd3fcc84644DdD6b96F7C741B1562B82f9e004dC7",
            "entry_point_selector": "0x02e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e"
        }
    },
    "id": 1
}
```

![image](https://github.com/NethermindEth/juno/assets/16260675/7efdb5c2-15fc-474e-9ed6-1a4d2ebf1e19)

**Comment by omerfirmak** [comment]
Ran a quick benchmark and profiled it briefly. Looks like most of the extra time is spent in fetching and unmarshaling of the pending block. Caching or entirely moving the pending block to in-memory should help quite a lot.

**Comment by wojciechos** [comment]
Fixed by: https://github.com/NethermindEth/juno/commit/d1dd18a74709284960ea909ca40514eca81522fb
