### ISSUE TITLE
Getting '63: Unexpected error occured' error when reading ERC20 balance on new block

### ISSUE THREAD

**Issue by lazarmitic** [NethermindEth/juno#1442]
Hello, when I try to read balance for a block that has just been synced (latest block) I'm getting error: (when fetching this balance I provide block number to fetch data from, even if block is latest one).

```
Unexpected error happened: LibraryError: 63: An unexpected error occurred
at RpcProvider.errorHandler (/home/ubuntu/indexer-prod/node_modules/starknet/src/provider/rpc.ts:98:13)
at RpcProvider.fetchEndpoint (/home/ubuntu/indexer-prod/node_modules/starknet/src/provider/rpc.ts:109:12)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at RpcProvider.callContract (/home/ubuntu/indexer-prod/node_modules/starknet/src/provider/rpc.ts:418:20)
```

Code that fetches balance retries to fetch balance again if request fails, and after couple of retires balance is successfuly fetched.

Also, If I try to fetch balance for older blocks, it works fine.

**Comment by lazarmitic** [comment]
If latest block is `418,811` and I try to fetch balance like this it fails sometimes:
```
    result = await tokenContract.balanceOf(accountAddress, {
      blockIdentifier: 418811,
    });
```

even if I don't specify block number, and do it like this, it still fails, and only succeeds after few reties:

```
    result = await tokenContract.balanceOf(accountAddress);
```

But if I try to fetch data from any past block, it works always, for example:
```
    result = await tokenContract.balanceOf(accountAddress, {
      blockIdentifier: 150000,
    });
```

**Comment by lazarmitic** [comment]
My guess is that there is some delay in data sync process, and it takes some time for all data inside latest block to becoma available? This is just a wild guess based on what I expirienced.

**Comment by omerfirmak** [comment]
Hey 👋 

You are getting "throttled" by your node. Try setting a higher `--max-vms`. Let me know how it goes, might be able to provide more details tomorrow.

**Comment by lazarmitic** [comment]
Thanks for info. Setting --max-vms to 16 solved the issue (I have two cores on AWS EC2 instance). But it's weird that it thorws error with 2 vms, shouldn't it process all requests, just slower?

**Comment by omerfirmak** [comment]
> shouldn't it process all requests, just slower?

Once Juno reaches the parallel vms limit (ie max-vms number of concurrent requests), it queues same number of requests to be processed after the first ones finish. If the queue is full, it starts to reject incoming requests.

So, if max-vms is set to 2; you can have 2 VM-related requests in flight and 2 in the queue, then it starts to reject.

Closing the issue for now, feel free to re-open it or join our Telegram channel that you can find a link to in the README.

**Comment by lazarmitic** [comment]
Thanks for the explanation. My feedback here would be to update error message for rejected requests so that users know what is going on. Second thing, I'm not sure if possible, is to allow users to set max queue lenght as startup param. This way I can keep my number of vms low (to avoid overloading instance), and still processing all requests without rejections. Thanks again for quick response.
