### ISSUE TITLE
Implement basic `uint128` type

### ISSUE THREAD

**Issue by joshklop** [NethermindEth/juno#1448]
Or use third-party package if there's a good one. I think `net` contains an un-exported `uint128` implementation we can use as inspiration.

Context: https://github.com/NethermindEth/juno/pull/1447#discussion_r1402009510

**Comment by joshklop** [comment]
Hi! Something similar would make sense (struct with hi, lo uint64s). There is no need to implement receivers and methods we wouldn't use in Juno; adapter functions/receivers to convert to/from `felt.Felt`s are probably all we want right now.

**Comment by anubhavitis** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/juno).

### My background and how it can be leveraged
I have over 2 years of experience in building Go-based applications, having worked with companies like CoinSwitch and currently Fileverse. I have designed, built, and deployed services from scratch that cater to hundreds of thousands of users daily. My expertise spans supporting both Web2 applications and Web3 dApps, making me well-equipped to contribute effectively to your project

### How I plan on tackling this issue
There are two ways to approach this:
1. Leverage the external package: https://github.com/lukechampine/uint128
2. Develop our own implementation based on our specific use case.

We can start with the first approach to test our use case and assess the impacts. Later, we can fork the repository and create our own implementation, ensuring robustness and tailoring it to our needs.

**Comment by derrix060** [comment]
Changing the
