### ISSUE TITLE
Add customizable cache size option for pebble

### ISSUE THREAD

**Issue by wojciechos** [NethermindEth/juno#1458]
The fixed 8MB cache size in Juno's Pebble database seems to be a performance bottleneck, particularly for starknet_call which are db-intensive.
```
From pebble.Options
	// Cache is used to cache uncompressed blocks from sstables.
	//
	// The default cache size is 8 MB.
	Cache *cache.Cache
```

**Proposed Solution:**
Implement a configurable cache size for Pebble, similar to [Geth's approach](https://github.com/ethereum/go-ethereum/blob/5ff929c22fb0315ebdb6efc5a871469f70522850/ethdb/pebble/pebble.go#L183-L222). This would allow us to adjust the cache size dynamically, potentially improving performance.

**First Step:**
- Add a command-line option (`--cache-size-mb`) to set the cache size in Pebble.

**Comment by Exca-DK** [comment]
I can work on it unless it's already taken.

**Comment by wojciechos** [comment]
@Exca-DK Sure, go for it. It's not taken yet.

**Comment by wojciechos** [comment]
> I can work on it unless it's already taken.

Sure, go for it. It's not taken yet.

**Comment by omerfirmak** [comment]
Done in #1471
