### ISSUE TITLE
Add `Network` bucket

### ISSUE THREAD

**Issue by joshklop** [NethermindEth/juno#1460]
Check it on startup to ensure the user provided a compatible network. Otherwise, Juno will revert the entire chain block-by-block.

Requires a migration. If the db is non-empty, we can use the first block hash to the determine the network.

**Comment by omerfirmak** [comment]
> ensure the user provided a compatible network

after the first startup, we can allow user to entirely omit the `--network` flag as well.

**Comment by joshklop** [comment]
> after the first startup, we can allow user to entirely omit the --network flag as well.

That's a really good idea! In the PR, Juno populates the `Network` bucket during the migration, which is after we've used the `cfg.Network` value to setup all of the services in `node.New`.

I propose we move database setup outside of `node.New`. Something like:

1. in `cmd/juno.go`: create the `db.DB` using the db path the user supplied.
2. `node.SetupDatabase`: takes a `db.DB` and applies migrations, returns the network.
3. Caller sets `cfg.Network` to the value found in the `Network` bucket, warning the user if the two network values differ.
4. `node.New`: takes a `db.DB`, `node.Config`, and `version` string.

**Comment by joshklop** [comment]
We should probably do that with the L1 service, too (move some setup outside of `node.New`). Then `node.New` will be side-effect-free + the config will be 100% consistent by the time it is passed to `node.New`.

**Comment by omerfirmak** [comment]
Done in #1486
