### ISSUE TITLE
Caching for transactions received

### ISSUE THREAD

**Issue by stranger80** [NethermindEth/juno#1529]
Implement caching for transactions received, so that `starknet_getTransactionStatus` always returns the status of a transaction that had just been forwarded to Starknet gateway. (see point 1 of: https://demerzelsolutions.slack.com/archives/C02UDC3AZHQ/p1701826699955059)

See a relevant PR by @kirugan - a good starting point for this feature.

**Comment by joshklop** [comment]
Relevant PR for reference https://github.com/NethermindEth/juno/pull/1134

**Comment by eliotstock** [comment]
Hey @joshklop we continue to discuss this in that Slack thread (link above) so have a look there before doing any work on this.
