### ISSUE TITLE
Does `cairoVMExecute` commit one extra time?

### ISSUE THREAD

**Issue by Lawliet-Chan** [NethermindEth/juno#1602]
I saw this line that you [commit state](https://github.com/NethermindEth/juno/blob/main/vm/rust/src/lib.rs#L338) after [executing txs](https://github.com/NethermindEth/juno/blob/main/vm/rust/src/lib.rs#L269-L273)
BUT the `transaction.execute()` already has `state.commit()`,  https://github.com/starkware-libs/blockifier/blob/main/crates/blockifier/src/transaction/transactions.rs#L59

Does `cairoVMExecute` commit one extra time?

BTW, Why you create a new `CachedState` [here](https://github.com/NethermindEth/juno/blob/main/vm/rust/src/lib.rs#L264) to pass in `t.execute()`? 
in Blockifier, there is a `CachedState` to [wrap the given state](https://github.com/starkware-libs/blockifier/blob/main/crates/blockifier/src/transaction/transactions.rs#L53)

**Comment by omerfirmak** [comment]
> BTW, Why you create a new CachedState [here](https://github.com/NethermindEth/juno/blob/main/vm/rust/src/lib.rs#L264) to pass in t.execute()?

The state created there is needed to be able to get per-txn state diffs that full nodes are expected to serve thru RPC. It holds changes that next transaction makes. Before switching to the next txn, we flush (ie commit) the changes to the [shared state](https://github.com/NethermindEth/juno/blob/96576b51a5f7909e9125625c92a07eccbdc80e75/vm/rust/src/lib.rs#L211).

> in Blockifier, there is a CachedState to [wrap the given state](https://github.com/starkware-libs/blockifier/blob/main/crates/blockifier/src/transaction/transactions.rs#L53)

Yeap, but sadly that state is not accessible to the caller (caller being us in this case) to be able to extract the per-txn state changes.

Will close this issue, feel free to join our telegram channel (you can find the invite link on our README) for further discussions. Would love to chat.
