### ISSUE TITLE
ERC 4844 support

### ISSUE THREAD

**Issue by stranger80** [NethermindEth/juno#1687]
- Change in block header content
- Blockifier update
- Fee estimations

Note: summary of SN 0.13.1 is found here: https://docs.google.com/document/d/16CyAZw8FnaxY8djZPF9cclwjARsj45940z787XtLHAM/edit#heading=h.rfqrb07r2gek 

Need effort and ETC info to feedback to StarkWare

# Conceptual Changes
Starknet v0.13.1 deals mostly with stability and performance improvements. The following items cover the changes feature-wise:

1. Starknet will use EIP4844 and send state diffs as blobs rather than calldata. This means that we need to add the notion of data_gas to Starknet blocks.
2. Pricing
  a. The gas prices of various Starknet operations will be reduced due to the adoption of EIP4844 alongside other improvements.
  b. The pricing for calldata and class declaration will change.
3. Bytecode segmentation – changing the definition of a compiled class hash so that only the used functions of a contract will be loaded into memory during the proof.

**Comment by AryanGodara** [comment]
@stranger80 Can I please work on this issue? I asked @jelilat too, in case someone else isn't working on this one already.
But it is a bigger issue, which will take me some time to work on. Could you please help me a bit on how to break this down into different tasks, and tackle them 😅

**Comment by stranger80** [comment]
Hi @AryanGodara, thanks for reaching out. In fact this will be included in the next Juno release, expected tomorrow, so we have that covered already.

**Comment by AryanGodara** [comment]
@stranger80 Oh, that's awesome :D
Is there any other issue you think I could work on? Something which anyone else isn't working on at the moment?
I've been following the repo and would love to make some good contributions :D

**Comment by IronGauntlets** [comment]
Closing as this is implemented by Juno v0.11.0
