### ISSUE TITLE
Implement Starknet 0.13.1 interim compatibility

### ISSUE THREAD

**Issue by stranger80** [NethermindEth/juno#1701]
Provide compatibility with Starknet FGW 0.13.1 before implementing RPCv0.7.

Tasks:
- [ ] Upgrade Cairo compiler and `blockifier` dependencies
- [ ] Adjust SN Feeder Gateway interface to adapt to new request/response formats (see https://docs.google.com/document/d/16CyAZw8FnaxY8djZPF9cclwjARsj45940z787XtLHAM/edit#heading=h.qow0pia4usyu sections 'FGW request/response' and 'FGW response object → RPC response object'
- [ ] Check backwards compatibility (ie. will the changes above work with SN FGW 0.13.0 on testnet???)

**Comment by rianhughes** [comment]
Upgrade the compiler and blockifier dependencies (cairo 2.6.0 / blockifier 0.5.0)

**Comment by rianhughes** [comment]
There is now a 6th point in FGW request/response "Transaction receipt refactor"
