### ISSUE TITLE
Juno + Lava guide

### ISSUE THREAD

**Issue by rianhughes** [NethermindEth/juno#1710]
Lavanet https://docs.lavanet.xyz/ allows users to run api providers, and gain rewards in decentralized manner.

An interesting issue would be to write a guide showing how users can run Juno on Lavanet

**Comment by LordGhostX** [comment]
Hi, I see Lava has a guide on running a Starknet RPC Node using Juno on their docs: https://docs.lavanet.xyz/starknet-node#juno-node

Does that resolve this issue? If it doesn't, please provide more information on what you want so I can help.

**Comment by rianhughes** [comment]
Yeah I think it does resolve this issue, cheers!
