### ISSUE TITLE
Juno RPC handler code tidying

### ISSUE THREAD

**Issue by stranger80** [NethermindEth/juno#1750]
- Refactor the RPC handler code in Juno 
  - improve breakdown into code files, etc. 
  - refer to @kirugan for more suggestions re refactoring
- Increase coverage of automated tests
- Implement a pattern of generating RPC handler code scaffolding from OpenAPI spec

**Comment by IronGauntlets** [comment]
> Implement a pattern of generating RPC handler code scaffolding from OpenAPI spec

Note the starknet spec is written in OpenRPC not OpenAPI and I don't think there is a good code generator in go for OpenRPC
