### ISSUE TITLE
No clear documentation and readme is not very helpful

### ISSUE THREAD

**Issue by fishonamos** [NethermindEth/juno#1765]
I was trying to integrate Juno to Carbonable Indexer and use it as data source but I discovered that Juno has no documentation. The readme is not readable and does not address a lot of issues. I think Juno should have a comprehensive documentation or  a detailed readme. I can help with that if the team can provide more details.

**Comment by wojciechos** [comment]
Hey! Can you share missing issues that should be covered? Also, you might find our docs here: https://juno.nethermind.io

**Comment by fishonamos** [comment]
The missing issue is that there should be a detailed step for integrating Juno with other services to use a data source. Although, it is pretty straightforward for some of us, I think is it something a lot of people will be interested in.

**Comment by LordGhostX** [comment]
@fishonamos 👋 

Thank you for opening this issue. I agree that the current docs aren't very detailed, and beginners can get lost, so https://github.com/NethermindEth/juno/pull/1857 resolves things. 

It also includes snippets to interact with a node using `starknet.js`, `starknet.go`, and `starknet.rs` aside `cURL` and the `WebSocket` server.

I'll be closing this issue. Feel free to open new ones to suggest more improvements in the future 🎉
