### ISSUE TITLE
Rename `trie/TransactionStorage` to `Storage`

### ISSUE THREAD

**Issue by IronGauntlets** [NethermindEth/juno#1783]
Reduce the overloading of the Transaction keyword.

**Comment by PabloVillaplana** [comment]
Hello, I would like to collaborate with this Good First Issue 👋🏽

**Comment by danielcdz** [comment]
@IronGauntlets Can this be assigned to me?

**Comment by CodeMongerrr** [comment]
This issue has been worked on completely right?

**Comment by diegoTech14** [comment]
**Hello @IronGauntlets**,
---

I'm Diego Duarte from Costa Rica, and I would like to help with this issue. I am a Web3 learner but I have experience developing in Web2.

For this issue I will change all the 'trie/TransactionStorage' matches to 'Storage'

Here is my [OD profile](https://app.onlydust.com/u/diegoTech14).

---
**Best rewards**,
**Diego Duarte**

Thanks for your consideration!

**Comment by kirugan** [comment]
I'm closing it because everything was imlemented already
