### ISSUE TITLE
TestClassV0 - Remove Goerli

### ISSUE THREAD

**Issue by stefanalfbo** [NethermindEth/juno#1807]
This is a sub-task to the issue #1758 that concerns the `TestClassV0`-tests. The tests are using the Goerli network that will be deprecated soon and therefore needs to be updated to use the Sepolia network instead.

**Comment by stefanalfbo** [comment]
One more @rianhughes that is ready for review, thanks in advance!

**Comment by tutex24** [comment]
May i try it?
