### ISSUE TITLE
Juno - Starknet 0.13.2 readiness

### ISSUE THREAD

**Issue by stranger80** [NethermindEth/juno#1864]
Ensure Juno readiness for Starknet 0.13.2 (as per the pre-release notes: https://docs.google.com/document/d/1QYSnp5c1tXkwcaxzujBtCOMjGGzXaOfXfs7wAYSwXqg/edit#heading=h.o2tpayxg0nwj)

Changes required:
[ ] Handle the [new block hash](https://docs.google.com/document/d/1EIlHskVJEyztS8eXRyPzd8cZwGuPcIKR5xUAIawzryk/edit#heading=h.200aq3cih8gm)
[ ] Update blockifier (expected changes: better error messages, parallelization of tracing a block, felt improvement)
[ ] FWG response update to `receipts` and `signatures`.

The parallelization of transaction execution is expected to be implicit so no API changes are expected. Apart from updating the blockifier no other changes are to be made on the Juno side for blockifier.

**Comment by rianhughes** [comment]
0.13.2 is currently supported
