### ISSUE TITLE
Implement the leaf range extraction and verification

### ISSUE THREAD

**Issue by stranger80** [NethermindEth/juno#1871]
As per the protobuf message specification in:
https://github.com/starknet-io/starknet-p2p-specs/blob/main/p2p/proto/snapshot.proto#L6

Implement Go modules for following operations
- ContractRangeRequest
- ClassRangeRequest
- ContractStorageRequest

**Comment by rianhughes** [comment]
See this branch for prototype implementation https://github.com/NethermindEth/juno/tree/proto/p2p-snap-sync
