### ISSUE TITLE
Receipt's `execution_resources` is missing  the required `data_availability` property

### ISSUE THREAD

**Issue by fracek** [NethermindEth/juno#1899]
I'm running the latest version of Juno (`0.11.9`) and I noticed that in some cases the `data_availability` property on the transaction is missing. This causes `starknet-rs` to error since the property is required.

Example request:

```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "starknet_getBlockWithReceipts",
  "params": [{"block_number": 0}]
}
```

Notice that the property is missing on all receipts.

**Comment by ashu26jha** [comment]
#1805

**Comment by fracek** [comment]
That's embarrassing, sorry! Will close this duplicate.
