### ISSUE TITLE
Nodes should reconnect to peers once they are online

### ISSUE THREAD

**Issue by weiihann** [NethermindEth/juno#1908]
Given the following scenario:

- `Node A` is a feeder node.
- `Node B` is a regular P2P node.
- `Node A` is online first. `Node B` syncs successfully from `Node A`.
- `Node A` goes offline. `Node B` no longer syncs from `Node A`.
- `Node A` goes online again. `Node B` should automatically detects that `Node A` is online again, and attempts to resync from it. 

However, that's not the case currently as `Node B` wasn't able to detect that `Node A` is online.

Not sure where the root cause is, but have some ideas for solution:
1. Persists the peer information somewhere and loads it whenever the node is started. In this way, `Node A` could notify `Node B` that it is online.
2. Regularly ping peers if they are online.

**Comment by IronGauntlets** [comment]
LIbp2p automatically detects when an old nodes come back online but it does take some time. This is probably due to how often the DHT table is refreshed. I would recommend to wait a little while longer.

**Comment by CodeMongerrr** [comment]
I want to try this one out, with the first way.

**Comment by CodeMongerrr** [comment]
@IronGauntlets as you said, the Node gets connected after waiting for a little longer time, so is it okay this way or should there be another way for connecting to the past peer automatically, (Eg. a flag)
