### ISSUE TITLE
Juno calling `eth_getBlockByNumber` extensively 

### ISSUE THREAD

**Issue by eiabea** [NethermindEth/juno#1915]
My `geth` node is currently re-syncing because of an scheme change from `hash` to `path`. I noticed a high cpu usage and a lot of the following logs from geth:

```
geth-1  | WARN [06-22|10:57:08.686] Served eth_getBlockByNumber              reqid=496507 duration="78.329µs"  err="finalized block not found"
geth-1  | WARN [06-22|10:57:08.686] Served eth_getBlockByNumber              reqid=496508 duration="23.214µs"  err="finalized block not found"
geth-1  | WARN [06-22|10:57:08.686] Served eth_getBlockByNumber              reqid=496509 duration="25.559µs"  err="finalized block not found"
geth-1  | WARN [06-22|10:57:08.687] Served eth_getBlockByNumber              reqid=496510 duration="54.814µs"  err="finalized block not found"
```

After stopping `Juno` the logs stopped. Looks like `Juno` gets stuck in some kind of loop trying to get the block desperately

**Comment by weiihann** [comment]
Probably because there's no limit mechanism before retrying, as shown [here](https://github.com/NethermindEth/juno/blob/main/l1/l1.go#L170-L183). Let me do a quick fix.
