### ISSUE TITLE
Unable to run juno in p2p mode over public network

### ISSUE THREAD

**Issue by derrix060** [NethermindEth/juno#1970]
With the current implementation of the p2p mode, one is required to provide the current node address via `--p2p-addr`.

This address will later on be gossiped to the network [HERE](https://github.com/NethermindEth/juno/blob/06b233924168deb6ac72122999766d1c5aa62242/p2p/p2p.go#L209).

In order to use the p2p mode over a public network, I tried to set the p2p addr to a public one, but it failed:

```
# Of course the ip I used doesn't contain XXX, I just replaced for security reasons
juno ... -p2p-addr=/ip4/35.237.XXX.XXX/tcp/7777 ...

Error: set up p2p service: failed to listen on any addresses: [listen tcp4 35.237.XXX.XXX:7777: bind: cannot assign requested address]
```

Having a quick look at the code, it seems that there is no way to tell Juno what's my public IP.
Looking at what other people have done using the same lib, I found some examples documented to do something similar to what we are trying to do https://github.com/libp2p/go-libp2p/tree/master/examples/routed-echo

I've also found an up-to-date maintained project that is trying to do the same, p2p over public network: https://discuss.libp2p.io/t/minimal-public-network/1651, and on their implementation they do expose a flag to set the external address: https://gitlab.com/accumulatenetwork/accumulate/-/blob/main/pkg/api/v3/p2p/p2p.go#L99

So this issue is to implement a way to be able to use the p2p option over private AND public networks

**Comment by wojciechos** [comment]
> Can't imagine that each node user gonna set external IP address. If not then, almost every node start to gossip not reachable node. If there gonna be a lot of such nodes, whole network start to be slow. For sure there is some solution for this, maybe something like here: https://docs.libp2p.io/concepts/nat/autonat/ (?)

**Comment by derrix060** [comment]
I found some good documentation around how to fix this issue: https://github.com/libp2p/specs/blob/master/connections/hole-punching.md#vision

Basically we will need to consider and implement a few ways to go about it.  I found another example that uses a few interesting options from libp2p
https://github.com/taubyte/tau/blob/main/p2p/helpers/libp2p.go and https://github.com/taubyte/tau/blob/main/p2p/peer/peer.go

Some points to consider from libp2p:
- [EnableHolePunching](https://github.com/libp2p/go-libp2p/blob/76b266558bb77d71106788f68931ce1ad0adf38a/options.go#L536)
- [EnableAutoRelayWithPeerSource](https://github.com/libp2p/go-libp2p/blob/76b266558bb77d71106788f68931ce1ad0adf38a/options.go#L340)
- [EnableAutoNATv2](https://github.com/libp2p/go-libp2p/blob/76b266558bb77d71106788f68931ce1ad0adf38a/options.go#L614)
- [EnableNATService](https://github.com/libp2p/go-libp2p/blob/76b266558bb77d71106788f68931ce1ad0adf38a/options.go#L371)
- [EnableRelayService](https://github.com/libp2p/go-libp2p/blob/76b266558bb77d71106788f68931ce1ad0adf38a/options.go#L295)
