### ISSUE TITLE
Draft: pass cairo steps as a header

### ISSUE THREAD

**Issue by kirugan** [NethermindEth/juno#1981]
We need to return step count for all blockifier executions as a header. Right now we have:
```
let res = match txn.unwrap() {
            Transaction::AccountTransaction(t) => {
                ....
                t.execute(&mut txn_state, &block_context, charge_fee, validate)
            }
            Transaction::L1HandlerTransaction(t) => { 
                ....
                t.execute(&mut txn_state, &block_context, charge_fee, validate)
            }
        };
```
`t.execute` returns structure like this one:
```
pub struct CallInfo {
    pub call: CallEntryPoint,
    pub execution: CallExecution,
    pub resources: ExecutionResources,
    pub inner_calls: Vec<CallInfo>,

    // Additional information gathered during execution.
    pub storage_read_values: Vec<Felt>,
    pub accessed_storage_keys: HashSet<StorageKey>,
}
```
You can get current execution steps from `callInfo.resources.n_steps`. Pass it as a header back to a caller in `X-Cairo-Steps` header. 

Open questions:

- should we aggregate cairo steps for all transactions in 1 request?
- do we need to return the header for all calls that call blockifier?

**Comment by eliotstock** [comment]
- should we aggregate cairo steps for all transactions in 1 request?
  - Yes, I believe so. We're using these for large multi-calls and are interested in the number of Cairo steps for all transactions in the HTTP request.
- do we need to return the header for all calls that call blockifier?
  - Yes, all calls that execute any Cairo steps at all, imo.

**Comment by obasekiosa** [comment]
```rs
#[derive(Clone, Debug, Default, Deserialize, Serialize, Eq, PartialEq)]
pub struct ExecutionResources {
    pub n_steps: usize,
    pub n_memory_holes: usize,
    #[serde(with = "crate::types::builtin_name::serde_generic_map_impl")]
    pub builtin_instance_counter: HashMap<BuiltinName, usize>,
}
```
