### ISSUE TITLE
Add readiness endpoint for synced node

### ISSUE THREAD

**Issue by kirugan** [NethermindEth/juno#2052]
This feature was requested from [tg channel](https://t.me/StarknetJuno/1195). 
We need to add `/ready/synced` (we can discuss actual endpoint path later) endpoint that will return 200 http code if node is fully synced (withing N blocks maybe?) otherwise it should return 503 http code. Similar to what [pathfinder does](https://github.com/eqlabs/pathfinder?tab=readme-ov-file#synced)

**Comment by obasekiosa** [comment]
Why have a dedicated enpoint when 
we can use the HEAD/OPTIONS method for all rpc endpoints to check if they are ready (like a pre-flight check).
Use status code or header value that says "how synced the node is"?

**Comment by kirugan** [comment]
>  Use status code or header value that says "how synced the node is"?

How is this different from `/ready/synced` endpoint? instead of sending the header from all endpoints we can have dedicated endpoint for that.

**Comment by obasekiosa** [comment]
> > Use status code or header value that says "how synced the node is"?
> 
> How is this different from `/ready/synced` endpoint? instead of sending the header from all endpoints we can have dedicated endpoint for that.

it would reduce the number of calls to just one and eliminate an extra endpoint.

**Comment by kirugan** [comment]
We decided to keep `/ready/sync` only (see https://t.me/StarknetJuno/1224)
