### ISSUE TITLE
Update ResourceBounds to use spec.Uint128

### ISSUE THREAD

**Issue by derrix060** [NethermindEth/juno#2237]
Superseeding https://github.com/NethermindEth/juno/issues/1448, there is now a function that will create a uint128: https://github.com/NethermindEth/juno/blob/65c0d6c693d99b880a635a6ea7e6bbba09e27570/adapters/core2p2p/felt.go#L49

The goal for this ticket is to update the ResourceBounds in transaction.go to use that

**Comment by RuneRogue** [comment]
I am a blockchain and DeFi developer . I am having experience of 1 year . I am currently working as a Blockchain Researcher and Developer. My Experience in programming language like Go , Rust , Java will help me to solve this issue.
