### ISSUE TITLE
Installation Prerequisites Instruction

### ISSUE THREAD

**Issue by TheCookieLab** [NethermindEth/juno#2274]
Just FYI the instructions call out:

> A C compiler: gcc or clang.

implying there is a choice, however with just clang the build failed with:

> imports github.com/NethermindEth/juno/jemalloc: build constraints exclude all Go files in /home/juno/jemalloc

Installing gcc resolved the issue. This is on Ubuntu 22.04.5 LTS and go 1.23.3.

**Comment by weiihann** [comment]
Thanks for this observation
