### ISSUE TITLE
Handle log level from settings

### ISSUE THREAD

**Issue by stdevMac** [NethermindEth/juno#228]
The log level now is set by default at the beginning of the app, we should be able to handle them using the configs

**Comment by vladimirovichkan** [comment]
I just want to ask where "the beginning of the app" is. I have found these two folders and I just don't understand where I should make changes (also to my knowledge I have to change the log file in internal/log)
![image](https://user-images.githubusercontent.com/98518570/174651766-7f4d2e70-0b1e-4b5a-980c-a90d0165d861.png)
I would be really thankful if you can help me to figure it out. 
Best regards Michael

**Comment by mv-kan** [comment]
I just want to make it clear. I need to create a new var in the config struct to be able to set log level from config file. 
1. But when I implement it how can I test my solution or something?
2. "Juno is node" and what does node mean in this context?
