### ISSUE TITLE
Split out mdbx so RPC client doesn't have to depend on it

### ISSUE THREAD

**Issue by archseer** [NethermindEth/juno#255]
We're not using the server code, but are instead using Juno as a RPC client. The client package depends on some `internal` bits which then pull in `mdbx` which introduces additional build constraints: it currently only builds via clang (https://github.com/NethermindEth/juno/issues/152).

**Comment by stdevMac** [comment]
Hello @archseer could you please provide more details about what you are using? we will have soon a great improvement on the RPC server, which might be interesting for you

**Comment by archseer** [comment]
We are only using the RPC client, not the RPC server. Our node will use Juno/Caigo to send transactions onto the network: https://github.com/smartcontractkit/chainlink-starknet/tree/develop/pkg/starknet

**Comment by archseer** [comment]
So we don't need an server with an embedded database, just a straightforward RPC client. `mdbx` is adding additional build constraints to our build process which might be a problem for us to ship.

**Comment by stdevMac** [comment]
Good, we will take a look at that and see how we can sort out those dependencies, and see if it is not solved on the new RPC implementation, in any case, we will solve it in the next couple of days, that works for you?

**Comment by archseer** [comment]
No rush! Just wanted to raise the issue early enough while you're still working on the RPC package. I think it would make sense to split out the types and common parts, then have two packages that depend on that: one for the server and one for the client.

**Comment by stdevMac** [comment]
When ready #313, this should be ready too
