### ISSUE TITLE
Crashing on CTRL+C

### ISSUE THREAD

**Issue by stdevMac** [NethermindEth/juno#260]
**Describe the bug**
Sometimes, when closing the app using `ctrl+c` the app crash

**To Reproduce**
1. Run the app
2. press CTRL+C
3. Repeat step 1 until the crash

**Expected behavior**
A clean close of the app without panic

**Screenshots**
App crashing
![image (4)](https://user-images.githubusercontent.com/35319980/177059783-2cf0d7af-01c8-4576-9162-fbdd71589ca5.png)

**Comment by D-DePablos** [comment]
I can't reproduce this on main, is this fixed now @stdevMac ?

**Comment by tshakalekholoane** [comment]
Fixed by #288.
