### ISSUE TITLE
Add cryptographic primitives used in StarkNet

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/juno#27]
https://starknet.io/documentation/transaction-structure-and-hash/

SIGNATURES
While StarkNet does not have a specific signature scheme built into the protocol, the Cairo language in which smart contracts are written does have an efficient implementation for ECDSA signature with respect to a STARK-friendly curve.

The STARK-friendly curve lives in F2p  with p=2251 + 17 · 2192 + 1 , and is defined by: 

y2= x3 + α · x + β

Where:

α= 1

β=3141592653589793238462643383279502884197169399375105820974944592307816406665
And the generator used in the ECDSA algorithm is G=gx, gy where:

gx=874739451078007766457464989774322083649278607533249481151382481072868806602
gy=152666792071518830868575557812948353041420400780739481342941381225525861407

For more details see our [repo](https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/crypto/starkware/crypto/signature/signature.py).

**Comment by tshakalekholoane** [comment]
See also this [Go implementation](https://github.com/dontpanicdao/caigo).
