### ISSUE TITLE
Make staging environment for docs

### ISSUE THREAD

**Issue by D-DePablos** [NethermindEth/juno#285]
RIght now, you can push changes to docs and break them in main.

**Comment by joshklop** [comment]
It looks like [something like this](https://github.com/NethermindEth/juno/blob/a5adfc3b7e08ce1cd63702d73fe623925289046c/.github/workflows/docs-staging-tests.yml#L1) might have existed in the past?

**Comment by joshklop** [comment]
[act](https://github.com/nektos/act#known-issues) looks like a good solution (thanks to @D-DePablos for pointing this out).
