### ISSUE TITLE
Add unit tests for the main package

### ISSUE THREAD

**Issue by joshklop** [NethermindEth/juno#301]
Right now, we don't test anything in the main package (`cmd/juno`). With [recent](https://github.com/NethermindEth/juno/pull/288) [PRs](https://github.com/NethermindEth/juno/pull/295), the main package has become much more modular and easier to test.

This is also be a good opportunity to consider moving configuration-specific logic such as [`loadConfig`](https://github.com/NethermindEth/juno/blob/2cff0703cbc73b9248be62dd80faae1303c4154b/cmd/juno/main.go#L146) to the `config` package.

**Comment by IronGauntlets** [comment]
#359
