### ISSUE TITLE
Block hash calculation

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/juno#31]
Add block hash calculation:

BLOCK HASH
A block hash is a hash of the block’s header elements.

Specifically:

pedersen_hash(
   parent_block_hash,block_number,
   new_global_root,sequencer,
   creation_time, transaction_commitment, transaction_count
   event_commitment, event_count, protocol_version, 
   extra_data
)
In StarkNet Alpha, each component that is not yet implemented is replaced with 0.

The code for the block hash generation can be found [here](https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/services/api/feeder_gateway/block_hash.py#L13).

**Comment by jelilat** [comment]
Done in https://github.com/NethermindEth/juno/pull/467
