### ISSUE TITLE
Implement RPC health_check endpoint

### ISSUE THREAD

**Issue by stdevMac** [NethermindEth/juno#324]
**Is your feature request related to a problem? Please describe.**
We should implement an health_check endpoint like this one on the [Nethermind client](https://docs.nethermind.io/nethermind/ethereum-client/monitoring-node-health#enabling-and-configuring-health-checks)

**Describe the solution you'd like**
Create a new RPC endpoint, that can be fixed, query the sync status, and any other info from the node. 
For more details, reach @stdevMac.

**Comment by tshakalekholoane** [comment]
I think this should be namespaced for consistency so maybe something like `juno_healthCheck`. See the [following examples](https://geth.ethereum.org/docs/rpc/server).

**Comment by tshakalekholoane** [comment]
One of the fields returned should probably also be an indicator of the number of blocks synced so that the user knows the range blocks they can execute calls against.
