### ISSUE TITLE
PR template

### ISSUE THREAD

**Issue by adriantpaez** [NethermindEth/juno#328]
I think the current PR template isn't the best because:

- Almost all the time I delete many things because I don't feel like necessary for my PR changes
- The usage of task lists to select the change type creates a GitHub task count on the PR list, that's distracting to me because I think PR is not complete yet. The same is happening for select if tests are required and done. See the **2 of 12 tasks** in the next image:
<img width="486" alt="image" src="https://user-images.githubusercontent.com/44682532/183084840-04028fdc-bc6e-45b1-be79-f2023ec39ea6.png">

# Template proposal

```
Fixes | Closes | Resolves #

## Description

_Explanation about why the PR is necessary_

## Changes:

- Change 1
- Change 2

## Types of changes

_Leave only the ones that describe your changes, remove the rest. Can remove this line too_

- Bugfix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Update
- Code style update (formatting, renaming)
- Refactoring (no functional changes, no api changes)
- Build related changes
- Other (please describe): 

## Testing
**Requires testing**: Yes/No
**Did you write tests??**: Yes/No
```

---

Fixes | Closes | Resolves #

## Description

_Explanation about why the PR is necessary_

## Changes:

- Change 1
- Change 2

## Types of changes

_Leave only the ones that describe your changes, remove the rest. Can remove this line too_

- Bugfix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Update
- Code style update (formatting, renaming)
- Refactoring (no functional changes, no api changes)
- Build related changes
- Other (please describe): 

## Testing
**Requires testing**: Yes/No
**Did you write tests??**: Yes/No

**Comment by AntiD2ta** [comment]
I see your point and I agree. I created that PR template and although the task count doesn't distract me, I find it a bit annoying sometimes. I can change it to your proposal after confirmation. Your proposal looks good to me. I would organize the _Type of changes_ in a way that the most used changes are the first and it is easier to delete the rest, so we can also avoid the deletion problem you mentioned.
