### ISSUE TITLE
Add function selectors support

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/juno#33]
FUNCTION SELECTOR
A function selector is an identifier through which the function is callable in transactions or in other contracts. The selector is the sn_keccak hash of the function name, encoded in ASCII.

**Comment by tshakalekholoane** [comment]
Closed by #231 [here](https://github.com/D-DePablos/juno/blob/fe4ff32a34696d4704b36a4991641f452d065776/cmd/juno-cli/cli/estimateFee.go#L31-L34).
