### ISSUE TITLE
Call shutdown if error is caught

### ISSUE THREAD

**Issue by joshklop** [NethermindEth/juno#336]
**Problem**
If an error is caught in [`checkErrChs`](https://github.com/NethermindEth/juno/blob/7735bff86b9e243266dbe6070a329a949409bda0/cmd/juno/main.go#L397), we immediately exit with a log message.

**Solution**
Call [`shutdown`](https://github.com/NethermindEth/juno/blob/7735bff86b9e243266dbe6070a329a949409bda0/cmd/juno/main.go#L362), attempting to exit cleanly without a stack trace.

**Comment by stdevMac** [comment]
closing because of https://github.com/NethermindEth/juno/pull/359
