### ISSUE TITLE
Sync returning 0 on starknet_blockNumber before first iteration

### ISSUE THREAD

**Issue by stdevMac** [NethermindEth/juno#361]
**Describe the bug**
When the server starts, the `starknet_blockNumber` RPC returns 0 while the first block isn’t synched, including the case when I’m restarting the sync from a block > 0. We need to update this value before starting the sync.

**Expected behavior**
Return the real value that we have already synced.

**Comment by adriantpaez** [comment]
Also, check this
![image](https://user-images.githubusercontent.com/44682532/185418194-c297e3fb-ba70-4c90-8342-06b8de1b3766.png)
The `starting_block_hash` is `nil` and the sync is running
