### ISSUE TITLE
Taking too long to close the node

### ISSUE THREAD

**Issue by stdevMac** [NethermindEth/juno#396]
**Describe the bug**
While updating the node, takes a lot of time close the node.

**To Reproduce**
1. Run the node
2. Press Ctrl+C

**Expected behavior**
Close the node as fast as possible with a grateful shut down.

```
Mon Sep  5 16:53:12 2022        INFO    apiCollector    Collector Started
^CMon Sep  5 16:53:23 2022      INFO    Shutting down Juno...
 Mon Sep  5 16:54:30 2022       INFO    apiCollector    StateUpdate collected   {"BlockNumber": 0}
Mon Sep  5 16:57:31 2022        INFO    Sync Service    Updated block info      {"Block Number": 0}
Mon Sep  5 16:57:31 2022        INFO    Shutting down JSON-RPC server...
```
3 min to close the node

**Comment by joshklop** [comment]
I have seen this as well. It may be because MDBX is writing the update to disk and needs to complete the transaction when we call `Close`. If this is the case, then making the database faster is the best solution. A temporary solution may be to cancel current transactions on `Close`.
