### ISSUE TITLE
Efficient Pedersen Hash 

### ISSUE THREAD

**Issue by IronGauntlets** [NethermindEth/juno#430]
In order to verify the blocks and transactions we need to have an efficient algorithm to calculate Pedersen Hash.

Golang's Benchmarking package should be used to compare the performance of the following:

1. Old Crypto Package implementation
2. StarkWare C++ implementation, which requires some go binding
3. Creating a new implementation written in Go

**Comment by omerfirmak** [comment]
>StarkWare C++ implementation, which requires some go binding 

I was working on [this](https://github.com/NethermindEth/crypto-cpp), I think it should be enough for our basic crypto needs for a good while. I bet we can upstream the changes in that fork as well.

**Comment by IronGauntlets** [comment]
closed #436
