### ISSUE TITLE
Design Efficient State Storage

### ISSUE THREAD

**Issue by joshklop** [NethermindEth/juno#433]
A flat storage is preferred for efficiency.

There are three parts to this task:
- [ ] State storage (class storage and contract instance storage)
- [ ] The Trie
- [ ] StateDiff/Changeset (i.e., storing historical state diffs)

**Comment by omerfirmak** [comment]
@joshklop Do you mind if I take a shot at implementing the Trie?

**Comment by joshklop** [comment]
I don't mind at all :)
