### ISSUE TITLE
[Bug/Security] panic in unmarshalTransactionReceipt

### ISSUE THREAD

**Issue by pventuzelo** [NethermindEth/juno#438]
# panic triggered inside unmarshalTransactionReceipt

We (@fuzzinglabs) triggered a panic in the unmarshalTransactionReceipt 

```sh
--- FAIL: Test_Reproduce_unmarshalTransactionReceipt (0.00s)
panic: unexpected type [recovered]
	panic: unexpected type

goroutine 6 [running]:
testing.tRunner.func1.2({0x793d60, 0x874b40})
	/usr/local/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1392 +0x39f
panic({0x793d60, 0x874b40})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/NethermindEth/juno/internal/db/transaction.unmarshalTransactionReceipt({0xc00002a4c8, 0x2, 0x2})
	/home/nabih/juno/internal/db/transaction/manager.go:296 +0x516
github.com/NethermindEth/juno/internal/db/transaction.Test_Reproduce_unmarshalTransactionReceipt(0x0?)
	/home/nabih/juno/internal/db/transaction/Fuzz_manager_reproducer_test.go:10 +0x37
testing.tRunner(0xc0000b3040, 0x8173d0)
	/usr/local/go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1486 +0x35f
exit status 2
FAIL	github.com/NethermindEth/juno/internal/db/transaction
```

## Expected Behavior

unmarshalTransactionReceipt should return an error.

## Your Environment

-  commit c5cc5578235cf9b875dceb23fa229e6467c3d660
-  go version go1.18 linux/amd64
-  Ubuntu 22.04

## Steps to reproduce
Create a test file in the folder : `internal/db/transaction`
```go
package transaction

import (
	"testing"
)

func Test_Reproduce_unmarshalTransactionReceipt(t *testing.T) {
	body := []byte("P(")
	_, err := unmarshalTransactionReceipt(body)
	if err != nil {
		return
	}
}

```
Run it with
```sh
go test
```

## Root cause
This panic causes the crash: 
https://github.com/NethermindEth/juno/blob/c5cc5578235cf9b875dceb23fa229e6467c3d660/internal/db/transaction/manager.go#L296

Similarly, there is another one in the marshalTransactionReceipt function that should be removed:
https://github.com/NethermindEth/juno/blob/c5cc5578235cf9b875dceb23fa229e6467c3d660/internal/db/transaction/manager.go#L242

**Comment by IronGauntlets** [comment]
Closing this issue since it is no longer relevant. The codebase has changed massively.
