### ISSUE TITLE
[Bug/Security] Invalid Felt value is not rejected

### ISSUE THREAD

**Issue by pventuzelo** [NethermindEth/juno#439]
# Invalid Felt value is not rejected

We (@fuzzinglabs) found a bug while doing differential fuzzing against Juno Pedersen's hash and felt implementation.

For this specific felt value (`0xfb01012100000000000000000000000000000000000000000000000000000000`), the following Pedersen/Felt implementations return: 
- Pathfinder: OverflowError
- starknet-rs: FromByteArrayError
- starkware-crypto-sys: Error code (1)
- Juno: 0xfb01012100000000000000000000000000000000000000000000000000000000

The Juno implementation of a felt object authorizes the creation with a value superior to the prime number used.

```
Prime number: 
0x800000000000011000000000000000000000000000000000000000000000001

Created Felt:
0xfb01012100000000000000000000000000000000000000000000000000000000
```

This can lead to creating a Pedersen Hash based on this invalid felt value.

## Expected Behavior

The program should reject the creation of the Felt.

## Your Environment

-  Juno commit: c5cc5578235cf9b875dceb23fa229e6467c3d660
-  cargo 1.66.0-nightly (082503982 2022-09-13) 
-  Ubuntu 20.04

## Steps to Reproduce

Testing program:
``` go
package main

import (
	"fmt"

	"github.com/NethermindEth/juno/pkg/crypto/pedersen"
	"github.com/NethermindEth/juno/pkg/felt"
)

func main() {

	a := new(felt.Felt).SetHex("fb01012100000000000000000000000000000000000000000000000000000000")
	b := new(felt.Felt).SetHex("0000000000000000000000000000000000000000000000000000000000000000")


	fmt.Printf("%s\n", pedersen.Digest(a, b).Hex())
}
```

**Comment by omerfirmak** [comment]
this is probably still the case 

https://github.com/ConsenSys/gnark-crypto/issues/346
