### ISSUE TITLE
JSON-RPC API for Blocks and Transactions

### ISSUE THREAD

**Issue by IronGauntlets** [NethermindEth/juno#449]
The following JSON-RPC endpoints need to be implemented, currently, without the `pending` tag:

- [ ] `getBlockWithTxHashes`
- [ ] `getBlockWithTxs`
- [ ] `getBlockTransactionCount`
- [ ] `getTransactionByHash`
- [ ] `getTransactionByBlockIdAndIndex`

**Comment by liusanchuan** [comment]
Hello, What the difference between getBlockWithTxHashes and getBlockWithTxs?
Is the getBlockWithTxs's input argument is (*Tx), while the getBlockWithTxHashes(Txhash)?
