### ISSUE TITLE
Add tests to clients package

### ISSUE THREAD

**Issue by joshklop** [NethermindEth/juno#488]
Currently, we [only test](https://github.com/NethermindEth/juno/blob/develop/clients/gateway_test.go) that json responses properly marshal into our corresponding struct types. We lack coverage for the actual business logic.

The task is to add tests for the client package (specifically `gateway.go`) by following the testing process mentioned in [Learn Go With Tests](https://quii.gitbook.io/learn-go-with-tests/). There is a HTTP server section which describes how to write tests using httptest package. For coverage stats and visuals, use `make test-cover`.

**Comment by liusanchuan** [comment]
please assign to me :) . I’m Lio.
