### ISSUE TITLE
 improvement : better printing of tries

### ISSUE THREAD

**Issue by thejdavid** [NethermindEth/juno#522]
Following the Todo: 

> create more meaningful representation of trie. In the current format string, storage is being
> printed but the value that is printed is the bitset of the trie node this is different from the
> storage of the trie. Also, consider renaming the function name to something other than dump.

TODO : 

changing the format string to print the following:
- key (which represents the storage key)
- path (as specified in the documentation)
- len (as specified in the documentation)
- bottom (as specified in the documentation)

**Comment by thejdavid** [comment]
will be starting soon

**Comment by IronGauntlets** [comment]
closing as no longer relevant
