### ISSUE TITLE
Refactor Trie Test

### ISSUE THREAD

**Issue by jelilat** [NethermindEth/juno#528]
- Test names should not have "_"
- Table test are being used incorrectly: they should be separated into subsets, see node_test.go
- Functions such as `Path` and `FindCommonKey` don't need to be public. Thus, they don't need to be tested explicitly.
- There are warning which ignore returned errors, returned errors should not be ignored.
- Add more test cases with different heights
- Add more complicated Put and Delete scenarios

**Additional context**
https://github.com/NethermindEth/juno/blob/develop/core/trie/trie_test.go#L15-L22

**Comment by liusanchuan** [comment]
@jelilat  Can you assign this to me?

**Comment by jelilat** [comment]
Sure. Done

**Comment by liusanchuan** [comment]
Hi @jelilat, can I split this issue into several PR commits?

**Comment by liusanchuan** [comment]
Hi @IronGauntlets , I'm not very sure about the least todo item "Add more test cases with different heights", I plan to "add a max height to Trie", then test create trie with different height. I wonder, is this way meet your require?

**Comment by IronGauntlets** [comment]
Hi @liusanchuan, 

First of all, thank you very much for your contributions!

What I meant by adding different heights is that we should have test cases that create trie of heights and check that the `Get`, `Put` and `Delete` operations work as expected, along with some edge cases. One of which is if you try to insert a key which is higher than the max value (calculated as `2^height -1`) there would be a panic. 

Adding max height is also required. If you would like you can work on these issues together. I believe #545 contains some work towards adding max height already
