### ISSUE TITLE
Client crashes when connection is lost

### ISSUE THREAD

**Issue by antiyro** [NethermindEth/juno#568]
**Description**
The Juno client crashes when network connection is lost with the following output :
``Error: read tcp xxxxxxx: read: network is unreachable``

**To Reproduce**
1. make juno
2. ./build/juno
3. Turn of network connection

**Expected behavior**
Wait for re connection 

**Additional context**
Papyrus/Pathfinder wait for re connection

**Comment by omerfirmak** [comment]
@antiyro which branch or version are you on?

**Comment by omerfirmak** [comment]
I just tried this on `develop` and it works as expected.
We deprecated the old versions and `master` is not up to date with the latest developments. Can you please try this on `develop` and see how that goes.

**Comment by antiyro** [comment]
I am on `develop` too

**Comment by IronGauntlets** [comment]
Hi @antiyro, the issue should be fixed after #556 is merged.

**Comment by omerfirmak** [comment]
Does it crash or exit gracefully? Can you share your full logs @antiyro

**Comment by antiyro** [comment]
Noted thanks 👍

**Comment by IronGauntlets** [comment]
@antiyro please try again. #556 has been merged.

**Comment by antiyro** [comment]
seems good thanks for you reactivity
