### ISSUE TITLE
Implement L1 Verification

### ISSUE THREAD

**Issue by jelilat** [NethermindEth/juno#671]
* [ ] #697 
* [ ] Determine whether a full Ethereum node can be used for L1 state retrieval instead of an archive node.
* [ ] Incorporate [`ethclient`](https://github.com/ethereum/go-ethereum/tree/master/ethclient)

**Comment by joshklop** [comment]
We may need to use something like `eth_getStorageAt` while syncing (we can binary search over a subset of the Ethereum chain to find state updates). Once synced with L1, we can use `eth_subscribe`.

**Comment by joshklop** [comment]
I'll a second issue for "L1 verification while syncing". That way #699 can be merged as an MVP while we take more time to think about the problem mentioned above.
