### ISSUE TITLE
L1 verification while syncing

### ISSUE THREAD

**Issue by joshklop** [NethermindEth/juno#709]
To ensure we are syncing the correct chain, we should verify L2 blocks with their L1 counterparts while syncing. We should try to do this without an archive node.

Example: if we are only subscribed to the latest L1 head and we happen to sync an incorrect chain from a malicious L2 peer, we won't know we are syncing the wrong chain until we reach the L1 head (the state roots won't match). We need to sync earlier L1 state updates to prevent this.

Related: #671

**Comment by joshklop** [comment]
We can get a reasonable compromise by using `eth_call` to get the L1 head very early in the sync process. That's what the linked PR does.

**Comment by IronGauntlets** [comment]
Closing as we fetch L1 Head during sync
