### ISSUE TITLE
Make colour codes configurable

### ISSUE THREAD

**Issue by jelilat** [NethermindEth/juno#716]
We should add a flag that lets users enable colour codes.

**Comment by tinoh9** [comment]
Hi, can I try this one? Thanks.

**Comment by omerfirmak** [comment]
Hi @tinoh9, sure. We would be glad:) Assigning it to you.

**Comment by tinoh9** [comment]
Should I create a new .go file which stores all color variables, and import it to all relevant string outputs that need to be colorized in CLI?

**Comment by omerfirmak** [comment]
> Should I create a new .go file which stores all color variables, and import it to all relevant string outputs that need to be colorized in CLI?

That sounds too complicated, see the [PR](https://github.com/NethermindEth/juno/pull/705) that disabled the color output. It should as simple as just passing the old value `EncodeLevel` function there.
