### ISSUE TITLE
Provide access to the underlying KV storage thru a gRPC service

### ISSUE THREAD

**Issue by omerfirmak** [NethermindEth/juno#743]
Pebble does not allow simultaneous access to the database. So for the users that need direct access to the DB, we should expose a gRPC service that provides the necessary access to the DB.

There are existing examples of such a service like;

https://github.com/ledgerwatch/interfaces/blob/master/remote/kv.proto

**Comment by fracek** [comment]
To go into more details how I use the remote kv api:

 * in [remote/kv.rs])(https://github.com/apibara/dna/blob/3fd1acd9178d005d71adf4dc27022645efe9bf1a/erigon_dna/src/remote/kv.rs) I created a simple abstraction over it, mostly to automate encoding and decoding of key and values.
 * in [remote/db.rs](https://github.com/apibara/dna/blob/3fd1acd9178d005d71adf4dc27022645efe9bf1a/erigon_dna/src/remote/db.rs) I use the abstraction of kv.rs to read data from Erigon's tables.
 * tables are in [erigon/tables.rs](https://github.com/apibara/dna/blob/3fd1acd9178d005d71adf4dc27022645efe9bf1a/erigon_dna/src/erigon/tables.rs), but it's not super related to the remote kv api.

**Comment by kirugan** [comment]
@fracek I checked rs code that you provided and here is resulting grpc spec. Could you please check is it enough? maybe I missed smth.
```
service DB {
  rpc Tx(stream Cursor) returns (stream Pair);
}

enum Op {
  FIRST = 0;
  SEEK = 1;
  SEEK_EXACT = 2;
  LAST = 3;
  NEXT = 4;
  PREV = 5;
}

message Cursor {
  Op op = 1;
  bytes k = 2;
}

message Pair {
  bytes k = 1;
  bytes v = 2;
}
````

**Comment by fracek** [comment]
It's also missing some code needed to implement [RemoteTx::open_cursor](https://github.com/apibara/dna/blob/3fd1acd9178d005d71adf4dc27022645efe9bf1a/erigon_dna/src/remote/kv.rs#L33)

Changes:

```proto
message Cursor {
  Op op = 1;
  string bucket_name = 2; // used to open a cursor in the given table
  uint32 cursor = 3; // used to specify which cursor to use
  bytes k = 4;
  bytes v = 5; // not used
}
```

```proto
message Pair {
  bytes k = 1;
  bytes v = 2;
  uint32 cursor_id = 3; // needed when using multiple cursors over one tx
  uint64 view_id = 4;   // not used
  uint64 tx_id = 5;     // not used
}
```

Also, if possible, it would be great to have the same package name and message types so that the same client can be reused between different implementations. You can drop methods in the service and even fields in messages and it will still work, as long as field ids are the same as the erigon's implementation.

**Comment by kirugan** [comment]
@fracek could you please check the result of https://github.com/NethermindEth/juno/pull/754 (branch kirugan/grpc-db) I need feedback :)

**Comment by fracek** [comment]
@kirugan I will use it to write a minimal version of the dna adapter over the weekend. That way we see immediately if all use cases are met. Thank you again for this, much appreciated!

**Comment by IronGauntlets** [comment]
done #754
