### ISSUE TITLE
Sanity check the user input to RPC module

### ISSUE THREAD

**Issue by omerfirmak** [NethermindEth/juno#748]
`json` package doesnt check that all the fields are present when unmarshaling a RPC argument from JSON.
`jsonrpc` checks that the non-optional arguments are there, but doesnt recursively check that the arguments are sane. (no nil ptrs, etc)

So for example, 

calling an endpoint with the following JSON which expects an `Arg` successfully reaches the handler.

``` json
{
   "val1" : "0xDEADBEEF"
}
```

``` golang
type Arg struct   {
   val1 *felt.Felt `json:"val1"`
   val2 *felt.Felt `json:"val2"`
}
```

and if handler assumes `val2` is non-nil, it can easily cause a panic

**Comment by joshklop** [comment]
Do `UnmarshalJSON`s on the appropriate `rpc` types solve this issue? It seems impossible for the `jsonrpc` module to know what fields are optional in a given situation.

We already do this for `BlockID`. Maybe we should do it for `EventsArg` to fix the [getEvents bug](https://github.com/NethermindEth/juno/pull/746#issuecomment-1534706870)?

**Comment by omerfirmak** [comment]
> Do `UnmarshalJSON`s on the appropriate `rpc` types solve this issue? It seems impossible for the `jsonrpc` module to know what fields are optional in a given situation.
> 
> We already do this for `BlockID`. Maybe we should do it for `EventsArg` to fix the [getEvents bug](https://github.com/NethermindEth/juno/pull/746#issuecomment-1534706870)?

validator package uses tags, so that information is encoded in the type. jsonrpc will only need to pass the value it creates to the validator package and it will extract the all the necessary criteria in runtime.

https://github.com/go-playground/validator/blob/master/_examples/simple/main.go
