### ISSUE TITLE
Report Transaction and Block statuses correctly in RPC responses

### ISSUE THREAD

**Issue by omerfirmak** [NethermindEth/juno#749]
Currently they are hard coded

https://github.com/NethermindEth/juno/blob/main/rpc/handlers.go#L90
https://github.com/NethermindEth/juno/blob/main/rpc/handlers.go#L328

after merging https://github.com/NethermindEth/juno/pull/699, these should be updated to reflect the correct statuses

**Comment by IronGauntlets** [comment]
fixed by #828
