### ISSUE TITLE
Reject any new L2 block that conflicts with the known L1 head

### ISSUE THREAD

**Issue by omerfirmak** [NethermindEth/juno#750]
If blockchain realizes that the local chain has diverged from the L1 canonical chain, it should stop accepting any new blocks even if they are perfectly fine and would be accepted normally.

In that case, it should return a special error that the sync package can match and take the necessary actions, like reverting some blocks.

Depends on #699 #707

**Comment by IronGauntlets** [comment]
Beacon sync implementation should solve this.
