### ISSUE TITLE
Make block hash calculation compatible with 0.11.1

### ISSUE THREAD

**Issue by jelilat** [NethermindEth/juno#757]
Note from Starknet

> 0.11.1 update related to block hash calculation: note that in 0.11.1 we start including the signatures of all transaction types except l1_handler.
> In the past, only invoke transactions had signatures and we included only those in the block hash. This persisted even when we had signatures for declare and other types, and is changed now in 0.11.1

**Comment by rianhughes** [comment]
I'll work on this one.

**Comment by rianhughes** [comment]
Leaving this link here for future reference https://github.com/NethermindEth/juno/pull/760
