### ISSUE TITLE
Start collecting metrics during runtime

### ISSUE THREAD

**Issue by omerfirmak** [NethermindEth/juno#783]
It could be all sorts of metrics

- JSON RPC request rates, response times, failures
- Gateway response times
- Block interval
- Block import times, verification times, failures
- Db read/write counts, delays

see https://prometheus.io/docs/guides/go-application/

**Comment by omerfirmak** [comment]
and eventually display them in grafana

**Comment by weiihann** [comment]
hey @omerfirmak, would like to contribute to this feature. Can you assign it to me?

**Comment by rianhughes** [comment]
https://github.com/NethermindEth/juno/pull/814

**Comment by joshklop** [comment]
Closing this optimistically since we have some metrics now. If we need a tracking issue for specific metrics, we can create one. But I think adding metrics as-needed is probably the best approach.
