### ISSUE TITLE
Export `jsonrpc.rpcErr` and make use of it in `rpc` package

### ISSUE THREAD

**Issue by omerfirmak** [NethermindEth/juno#796]
https://github.com/NethermindEth/juno/blob/7ca28f11b102744511831bbe6d92d83bf36f5b92/jsonrpc/server.go#L46-L59

in places like;

https://github.com/NethermindEth/juno/blob/7ca28f11b102744511831bbe6d92d83bf36f5b92/rpc/handlers.go#L755-L769

**Comment by rianhughes** [comment]
Currently the error messages in [juno/rpc/handlers.go] provides useful information to the caller that would be lost if we used `rpcErr`. 

For example, if a user submitted a transaction with an incorrect transaction version, rpcErr wouldn't tell them version was incorrect, only that some parameter they provided was incorrect. It would also return the same error if they used the correct version, but forgot some other field, etc.

**Comment by omerfirmak** [comment]
We can use Data field to return an arbitrary error message

**Comment by rianhughes** [comment]
https://github.com/NethermindEth/juno/pull/802
