### ISSUE TITLE
Handle L1 reorgs

### ISSUE THREAD

**Issue by joshklop** [NethermindEth/juno#826]
Right now we just store L1 updates in the database. Now that the `blockchain.Blockchain` can revert, we should handle L1 reorgs.

**Comment by omerfirmak** [comment]
> handle L1 reorgs

what do you mean by that exactly?

**Comment by joshklop** [comment]
Right now, if L1 reorgs, we delete the reorgs logs from the queue. If the reorg is longer than the queue length, we also need to update the L1 head in the db.

**Comment by joshklop** [comment]
I am open to that. It would simplify things a lot.

However, I think all nodes should use the same confirmation period. Otherwise, in the event of a reorg, the network will be temporarily partitioned. What do you think?

**Comment by omerfirmak** [comment]
> However, I think all nodes should use the same confirmation period

Agreed, I dont see a reason to make it configurable.
