### ISSUE TITLE
Handle batch requests concurrently

### ISSUE THREAD

**Issue by joshklop** [NethermindEth/juno#839]
From the JSON RPC 2.0 [spec](https://www.jsonrpc.org/specification#batch):

> The Server MAY process a batch rpc call as a set of concurrent tasks, processing them in any order and with any width of parallelism.

I think this is what the [todo](https://github.com/NethermindEth/juno/blob/69bfaebd17a4b3c9eb13e286714060983a0ea545/jsonrpc/server.go#L179) in the code is referring to.

**Comment by kirugan** [comment]
Can I work on this one? Sounds super cool

**Comment by joshklop** [comment]
Sounds great to me!

**Comment by IronGauntlets** [comment]
Done #851
