### ISSUE TITLE
Fetch the head's header only when verifying incoming blocks

### ISSUE THREAD

**Issue by omerfirmak** [NethermindEth/juno#855]
https://github.com/NethermindEth/juno/blob/main/blockchain/blockchain.go#L351

we fetch the entire block, but we are fine with fetching the header only.

**Comment by ItIsOHM** [comment]
Hey there, I am a beginner and want to contribute to this.

Regarding this issue, i suppose the solution would be to change "block *core.Block" in this function ->
` func verifyBlock(txn db.Transaction, block *core.Block) `
to "header *core.header"?

**Comment by omerfirmak** [comment]
Closed in #857
