### ISSUE TITLE
Add fuzzing tests

### ISSUE THREAD

**Issue by kirugan** [NethermindEth/juno#868]
Since go 1.18 we have a new kind of tests - [Fuzzing](https://go.dev/security/fuzz/). Looks like they can help us to find edge cases for tests

**Comment by aminsato** [comment]
> Since go 1.18 we have a new kind of tests - [Fuzzing](https://go.dev/security/fuzz/). Looks like they can help us to find edge cases for tests

For a start, which file do you suggest adding fuzzing tests to
