### ISSUE TITLE
Add authentication support to jsonrpc server

### ISSUE THREAD

**Issue by joshklop** [NethermindEth/juno#875]
Users should be able to send messages using `https` and `wss` protocols.

**Comment by lazyfuhrer** [comment]
I'd like to work on this. You can assign me @joshklop

**Comment by joshklop** [comment]
Awesome, thank you! Please note that this is a relatively large feature that could change quite a bit of code in the `jsonrpc` package. It would be great if you could post updates/questions here so we can resolve issues quickly and keep everyone in sync.

How do you plan to go about this?

**Comment by joshklop** [comment]
Maybe we should consider doing something similar, but under a `starknet` directory: https://github.com/ethereum/execution-apis/pull/297

What do you think?

**Comment by lazyfuhrer** [comment]
Yup can try that too. I'll give you the update
