### ISSUE TITLE
Better sorting of buffered transactions in storage update

### ISSUE THREAD

**Issue by joshklop** [NethermindEth/juno#903]
See [here](https://github.com/NethermindEth/juno/pull/900#discussion_r1258620454) for reference.

> Actually if we sort the slice of BufferedTransactions we get back from the routines in ascending contract address order, we might get an additional speed up. But it is not really worth it at this point. Will leave it to another PR.

cc @omerfirmak

**Comment by kirugan** [comment]
Done in PR #1882
