### ISSUE TITLE
Compare RWMutex vs BufferedTransaction performance

### ISSUE THREAD

**Issue by joshklop** [NethermindEth/juno#904]
Right now we use a buffered transaction in the contract storage update. We could use an RWMutex instead. We should investigate which is faster.

See [here](https://github.com/NethermindEth/juno/pull/900#discussion_r1258654639) for reference:

> I expected a lock to have a worse performance impact compared to memory allocations that we need for buffering.
But that is just my gut feeling. We can keep experimenting after merging this.
But regardless, we will have to implement a new type that wraps a transaction and protects it with a RWMutex.

cc @omerfirmak

**Comment by omerfirmak** [comment]
Gave this a try and confirmed my initial gut feeling. It should still make sense to use a RWMutex for #1096 tho.

```
RWMutex
BenchmarkMainnetBlock-16    	      10	 270091316 ns/op	 4110941 B/op	   81987 allocs/op
BenchmarkMainnetBlock-16    	      10	 274670927 ns/op	 4103562 B/op	   81969 allocs/op
BenchmarkMainnetBlock-16    	      10	 273553244 ns/op	 4108708 B/op	   81985 allocs/op


BufferedTransaction
BenchmarkMainnetBlock-16    	      10	 248140718 ns/op	 4546570 B/op	   87130 allocs/op
BenchmarkMainnetBlock-16    	      10	 246536244 ns/op	 4546748 B/op	   87134 allocs/op
BenchmarkMainnetBlock-16    	      10	 250365643 ns/op	 4544698 B/op	   87106 allocs/op
```

**Comment by omerfirmak** [comment]
pushed the code to [this](https://github.com/NethermindEth/juno/tree/omerfirmak/legacy-trace-block-err) branch

**Comment by omerfirmak** [comment]
Gave #1096 a try with a RWMutex, contention is really high that #1096 brings no benefit. Closing this one.

**Comment by omerfirmak** [comment]
Actually a RWMutex transaction is useful when used together with a BufferedTransaction to reduce contention.
