### ISSUE TITLE
Allow Juno to be configured by using environment variables

### ISSUE THREAD

**Issue by omerfirmak** [NethermindEth/juno#905]
So instead of using flags or config file, we should be able to use environment variables as configuration as well.

[see](https://pkg.go.dev/github.com/spf13/viper#AutomaticEnv) `viper.AutomaticEnv`

**Comment by pratham-bhatnagar** [comment]
I would like to work on this issue

**Comment by omerfirmak** [comment]
> I would like to work on this issue

Sure, go ahead :+1:

**Comment by lazyfuhrer** [comment]
Is it still open ? I'd like to work on this @omerfirmak

**Comment by IronGauntlets** [comment]
@lazyfuhrer it is still open, please go ahead.

**Comment by lazyfuhrer** [comment]
check #988 @omerfirmak

**Comment by 4ever9** [comment]
I've seen this issue inactive for about 2 months, so I'm trying to fix it.
pr: https://github.com/NethermindEth/juno/pull/1286
