### ISSUE TITLE
Add `/health` endpoint and return 200 for `/`

### ISSUE THREAD

**Issue by chichi13** [NethermindEth/juno#923]
Hello,

We're using several instances of juno / pathfinder binaries for our Starknet RPCs.
The root path (`/`) of pathfinder return a `405` : 

Do you think it's possible to add a `/health` endpoint returning 200 if the binary is running well for our Load Balancer Health Check ?
Furthermore, do you think it's possible to return `200` when there are no parameters given on the endpoint `/` please ?

**Comment by chichi13** [comment]
I'd like to add that if the `/` endpoint returns 200, it's not necessarily necessary to create the `/health` endpoint.

**Comment by omerfirmak** [comment]
>  Furthermore, do you think it's possible to return 200 when there are no parameters given on the endpoint / please ?

`/` is JSON RPC endpoint, so it only accepts POST requests with valid requests in the body. Deviating from that would be not spec complaint.

Can you define custom requests for Load Balancer Health Checks? If yes, the best way to actually asses health of the node would be sending an actual JSON RPC request.

**Comment by chichi13** [comment]
The Load Balancer can only GET and cannot send a request with JSON. The purpose of the Load Balancer health check is very simplistic (and should remain so), it's just a very basic request to check that the site returns 200, if it doesn't return 200 --> KO

Here's another explanation of why I'd like the root path to return a 200 : we have quite a few bots spamming the root path `/`, which triggers alerts from our monitoring system because it returns 4XX errors (405 for Juno). To avoid this, returning `200` on `/` is a good solution.

**Comment by omerfirmak** [comment]
Got it, https://github.com/NethermindEth/juno/pull/925 should be part the next release.

**Comment by omerfirmak** [comment]
> we have quite a few bots spamming the root path /, which triggers alerts from our monitoring system because it returns 4XX errors (405 for Juno). To avoid this, returning 200 on / is a good solution.

Is there no way configure the monitoring system to ignore GET requests? Because JSONRPC doesnt support them, them failing is for sure not an issue.

**Comment by chichi13** [comment]
As we have multiple endpoints on our nginx server, this seems complicated to me.

I've just seen the PR, thanks for the change!
