### ISSUE TITLE
Link the Telegram chat in the README

### ISSUE THREAD

**Issue by joshklop** [NethermindEth/juno#928]

**Comment by lazyfuhrer** [comment]
Assign me @joshklop

**Comment by joshklop** [comment]
Thanks for offering to work on this @lazyfuhrer. If we could have an clickable Telegram icon similar to the Discord and Twitter icons, that would be amazing.

![image](https://github.com/NethermindEth/juno/assets/31332481/fafbbc2d-0147-4ddf-aa9a-fe6dd415f267)

**Comment by lazyfuhrer** [comment]
Can you provide me the telegram link and also in which branch should I make the PR ?

**Comment by joshklop** [comment]
Link: https://t.me/+skAz9cUvo_AzZWM8

Any branch name is fine. Maybe `lazyfuhrer/tg`?

**Comment by lazyfuhrer** [comment]
I've opened a PR at #932 please review
