### ISSUE TITLE
Allow for less than two return values in RPC handlers

### ISSUE THREAD

**Issue by joshklop** [NethermindEth/juno#933]
Right now RPC handlers must have two return values, and the second return value must be of type `*jsonrpc.Error`. It would convenient if the following three cases were supported:

- zero return values
- one return value (response or error)
- two return values, where the second must be an error <- we only support this right now

This is very similar to geth's RPC server [semantics](https://github.com/ethereum/go-ethereum/blob/7f756dc1185d7f1eeeacb1d12341606b7135f9ea/rpc/doc.go#L29-L30).

**Comment by IronGauntlets** [comment]
I am not sure how useful this would be since returning multiple values with the last value being an error is a go idiom.

Can you please explain which case would benefit from the 2 unimplemented options?

**Comment by joshklop** [comment]
Definitely low-priority.

> Can you please explain which case would benefit from the 2 unimplemented options?

One return value: some simple handlers like [juno_version](https://github.com/NethermindEth/juno/blob/8656316426923c131187873a8bf8df048e5864c8/rpc/handlers.go#L980) never return an error.

Zero return values: Probably useless. I forget what I was thinking here.

**Comment by joshklop** [comment]
Not needed. See linked PR above.
