### ISSUE TITLE
Add `revert_reason` to `rpc.TransactionReceipt`

### ISSUE THREAD

**Issue by omerfirmak** [NethermindEth/juno#934]
https://github.com/starkware-libs/starknet-specs/commit/338fd893db793dd6696ed55839048070fae5fa63

**Comment by joshklop** [comment]
I didn't include it because it's optional and I'm not sure what would go there. Cairo VM/Blockifier error? Does that mean we need to re-execute transactions in `rpc.TransactionReceipt`?

Would love it if I'm missing something here :)

**Comment by omerfirmak** [comment]
Feeder gateway provides the revert reason, so I dont think there is a reason to not serve them.

**Comment by joshklop** [comment]
Do we plan to store them?

**Comment by omerfirmak** [comment]
Yeah, do you think there is a reason not to?

**Comment by joshklop** [comment]
Just to save a few bytes in the receipts :)

And because the same information can be obtained (if desired) by simulating the transaction.

**Comment by omerfirmak** [comment]
> if desired

RPC doesnt have a way to specify that. So we would have to simulate the transaction (actually the entire block) when someone asks for a reverted transaction receipt, even if they are not really interested in the revert reason.

**Comment by joshklop** [comment]
I meant that one can send a second `simulateTransaction` RPC request. Agree that we definitely don't want to do it as part of the original call.

**Comment by omerfirmak** [comment]
> I meant that one can send a second simulateTransaction RPC request

Ah, I see. My bad. 
But I think they would have to use `starknet_traceBlockTransactions`. But it is a really costly call.
`simulateTransaction` is for arbitrary transaction, not for the transaction that are already in a block.

**Comment by joshklop** [comment]
Fair enough. We could ask wallet devs and Voyager if they would use the revert reason. I also want to check how Ethereum's api handles this.

**Comment by joshklop** [comment]
Ethereum [doesn't have](https://github.com/ethereum/execution-apis/blob/9c873c21d7d773d0df4b679b0bb37bf05aebadf2/src/schemas/receipt.yaml#L52-L113) revert reason in the receipt structure.

**Comment by omerfirmak** [comment]
We can make it configurable in the future. For now, we store anything and everything anyways :D

**Comment by joshklop** [comment]
Sounds good to me.
