### ISSUE TITLE
Implement Cairo0 class hash calculation

### ISSUE THREAD

**Issue by omerfirmak** [NethermindEth/juno#939]

**Comment by IronGauntlets** [comment]
Can you please provide more context? I thought we already agreed to only compute it on the rust side.

**Comment by omerfirmak** [comment]
> I thought we already agreed to only compute it on the rust side.

It is an additional rust dependency. It would be nice if we could avoid it. But we can decide to keep depending on it until the regenesis.

**Comment by IronGauntlets** [comment]
If it is as simple as reverting a previous commit where we removed Cairo0 Class Hash then we should do it.
