### ISSUE TITLE
Sync state from other nodes

### ISSUE THREAD

**Issue by tshakalekholoane** [NethermindEth/juno#95]
- [ ] Receive and propagate:

  - [ ] State diffs.
  - [ ] Transactions.
  - [ ] Events.

- [ ] Send state to new syncing nodes.

**Comment by tshakalekholoane** [comment]
- [ ] Receive and propagate:

  - [ ] State diffs.
  - [ ] Transactions.
  - [ ] Events.

- [ ] Send state to new syncing nodes

**Comment by stdevMac** [comment]
With the p2p network, this will change a lot in the way things are build, closing for now
