### ISSUE TITLE
Define our own trie.Key type

### ISSUE THREAD

**Issue by omerfirmak** [NethermindEth/juno#974]
We are using a third-party bitset library as our key type. But it is  not properly serialized to a big endian byte array. The maintainer is not acknowledging the issue, so there is no way to fix it upstream.

Define a simple key type like;

``` golang
type Key struct {
   Len byte
   Val felt.Felt
}
```

**Comment by IronGauntlets** [comment]
Is it not possible to infer the `len` from the `felt.Felt`?

**Comment by omerfirmak** [comment]
> Is it not possible to infer the `len` from the `felt.Felt`? 

Sadly, no. But instead of a felt, I opted for a byte array in the actual implementation.
