### ISSUE TITLE
Prepare Grafana dashboards for Prometheus metrics

### ISSUE THREAD

**Issue by omerfirmak** [NethermindEth/juno#979]
See #919

**Comment by wojciechos** [comment]
@joshklop recently we've added some additional metrics like `sync_blockchain_height` or `rpc_server_requests_latency`, so it requires to add some new visualisations

**Comment by IronGauntlets** [comment]
We can close this issue as we have a Grafana dashboard with metrics. We should create a new issue for any specific metric we want to display on the dashboard.
