### ISSUE TITLE
Implement `starknet_traceBlockTransactions`

### ISSUE THREAD

**Issue by IronGauntlets** [NethermindEth/juno#997]

**Comment by wojciechos** [comment]
Mismatch in Error Code and Message for `starknet_traceBlockTransactions`

For block which does not exists, for sample request e.g:
```
{
    "jsonrpc": "2.0",
    "method": "starknet_traceBlockTransactions",
    "params": {
        "block_hash": "0x233bfd9ba4c3a6ce28be2f9d97fcf9a74881024d3f6d9cb35b219585ca2c3b1"
    },
    "id": 1
}
```

I receive response like:
```{
    "jsonrpc": "2.0",
    "error": {
        "code": 24,
        "message": "Block not found"
    },
    "id": 1
}
```

while according to [spec](https://github.com/starkware-libs/starknet-specs/blob/0e859ff905795f789f1dfd6f7340cdaf5015acc8/api/starknet_trace_api_openrpc.json#L158C50-L158C68) it should be rather:

```
{
    "jsonrpc": "2.0",
    "error":  {
         "code": 26,
         "message": "Invalid block hash"
    },
    "id": 1
}
```
