### ISSUE TITLE
Cache previous Juno builds in Github Actions

### ISSUE THREAD

**Issue by IronGauntlets** [NethermindEth/juno#999]
After introducing rust dependencies compile time increased from several minutes to 15-18 minutes.

**Comment by IronGauntlets** [comment]
Please help @NethermindEth/angkor-juno

**Comment by stdevMac** [comment]
@IronGauntlets We need to look into this, but hard to say, since Rust builds are quite heavy, will see what can be optimized.

**Comment by omerfirmak** [comment]
I think #1041 should be enough for now

**Comment by omerfirmak** [comment]
Tests take around 1/3 of what it used to take now.

**Comment by stdevMac** [comment]
That's awesome! Thanks!
